import { getLocales } from 'expo-localization';

import { useAppPreferences, type AppLanguage } from '@/lib/app-preferences';

type SupportedLanguage = 'en' | 'ar';

export const languageLabels: Record<AppLanguage, string> = {
  system: 'System',
  en: 'English',
  ar: 'العربية',
};

const en = {
  common: {
    appName: 'Diabeto',
    back: 'Back',
    cancel: 'Cancel',
    clear: 'Clear',
    continue: 'Continue',
    no: 'No',
    optional: 'Optional',
    paste: 'Paste',
    remove: 'Remove',
    save: 'Save',
    send: 'Send',
    wait: 'Wait',
    yes: 'Yes',
  },
  tabs: {
    chat: 'Chat',
    guide: 'Guide',
    home: 'Home',
    log: 'Log',
    predict: 'Predict',
    settings: 'Settings',
  },
  home: {
    subtitle: 'Track risk, understand meals, and chat through healthier choices.',
    today: 'Today',
    quickRiskCheck: 'Start with a quick risk check.',
    predictionHelps: 'Your prediction data also helps Ribbon give more specific food and habit advice.',
    openPredict: 'Open Predict',
    guideBody: 'Balanced meal ideas and simple habit targets.',
    dailyLog: 'Daily Log',
    dailyLogBody: 'Record glucose, sleep, activity, water, meals, and notes.',
    chatBody: 'Ask Ribbon about meals, snacks, habits, or food photos.',
    settingsBody: 'Adjust appearance, language, colors, and Ribbon tone.',
    disclaimer: 'Diabeto is educational and does not replace medical diagnosis or care.',
  },
  onboarding: {
    pageTitles: ['Welcome', 'Terms', 'Health Details', 'Glucose Access', 'Ribbon'],
    startDiabeto: 'Start Diabeto',
    welcomeSubtitle:
      'A diabetes prevention assistant that estimates risk and gives practical habit advice from simple health details.',
    welcomeItems: [
      'Quick lifestyle-based risk estimate',
      'Personal advice from your details',
      'Optional AI chat for meals and food images',
    ],
    beforeStart: 'Before You Start',
    termsTitle: 'Terms of Service',
    termsBody:
      'Diabeto is for education and prevention support only. It does not diagnose diabetes, replace a doctor, or provide emergency care.',
    termsResponsibility:
      'You are responsible for checking important health decisions with a qualified healthcare professional.',
    privacyTitle: 'Privacy Policy',
    privacyBody:
      "Diabeto uses the details you enter to estimate risk and personalize the AI companion's replies. Chat messages and selected images may be sent to the configured Gemini API.",
    privacyWarning:
      'Do not upload private medical documents, IDs, or photos you do not want processed by the AI provider.',
    agreeTerms: 'I agree to the Terms of Service',
    understandPrivacy: 'I understand the Privacy Policy',
    yourDetails: 'Your Details',
    detailsHelp: 'These details help Diabeto make a first estimate. You can adjust them later.',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    years: 'years',
    activity: 'Activity',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    sugaryDrinks: 'Sugary drinks',
    rarely: 'Rarely',
    sometimes: 'Sometimes',
    often: 'Often',
    familyHistory: 'Family history of diabetes',
    glucoseAccess: 'Glucose Access',
    glucoseHelp: 'Not everyone can measure blood glucose at home. Diabeto will not require a glucose value.',
    canMeasureGlucose: 'Are you able to measure your blood glucose right now?',
    glucose: 'Glucose',
    whatThisMeans: 'What this means',
    glucoseMeaning:
      'If you cannot measure glucose, Diabeto estimates risk using age, BMI, family history, activity, and sugary drink habits. A lab glucose or A1C test can make the picture clearer later.',
    meetRibbon: 'Meet Ribbon',
    ribbonBody:
      'Ribbon is your Diabeto health companion. She can help you turn your risk estimate into practical meal ideas, food swaps, activity goals, and safer daily habits.',
    ribbonItems: [
      'Uses your saved health details when you chat',
      'Can review food or drink images you attach',
      'Requires your own Gemini API key from Google AI Studio',
      'Paste the key in Settings before using chat',
      'Keeps advice educational, supportive, and practical',
    ],
  },
  settings: {
    title: 'Settings',
    subtitle: 'Personalize Diabeto and Ribbon.',
    geminiApiKey: 'Gemini API Key',
    keyHelp: 'Ribbon uses your own Google AI Studio key. It stays on this device.',
    keyPlaceholder: 'Paste Gemini API key',
    getApiKey: 'Get an API key',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    colorTheme: 'Color Theme',
    colorThemeLabels: {
      sky: 'Sky',
      mint: 'Mint',
      violet: 'Violet',
      coral: 'Coral',
    },
    ribbonTone: 'Ribbon Tone',
    ribbonToneLabels: {
      warm: 'Warm',
      cold: 'Cold',
      aggressive: 'Aggressive',
      casual: 'Casual',
    },
    ribbonToneDescriptions: {
      warm: 'Default',
      cold: 'also known as Professional',
      aggressive: 'WARNING: You will be heavily insulted if you show images of unhealthy food.',
      casual: 'specifically designed for our gen z users, wassup',
    },
  },
  chat: {
    starter:
      'Hi, I am Ribbon. I can help you plan balanced meals, understand food choices, review images, and build habits that lower diabetes risk.',
    subtitle: 'Your Diabeto health companion.',
    keyNeeded: 'Gemini API key needed',
    usingAll: 'Using Predict data, daily logs, and chat memory',
    usingMemory: 'Using chat memory only',
    keyPanelTitle: 'Ribbon needs your Gemini API key.',
    keyPanelBody: 'Create a key in Google AI Studio, copy it, then paste it in Settings.',
    openSettings: 'Open Settings',
    attachImage: 'Attach image',
    attachImageMessage: 'Choose where the image should come from.',
    takePhoto: 'Take photo',
    choosePhoto: 'Choose photo',
    photoAccessNeeded: 'Photo access is needed before Ribbon can review an image from your library.',
    cameraAccessNeeded: 'Camera access is needed before Ribbon can review a new photo.',
    imageTooLarge: 'That image is too large. Please choose a smaller photo.',
    imageFailed: 'I could not process that image. Please choose a different photo.',
    addKeyBeforeChat: 'Add your Gemini API key in Settings before chatting with Ribbon.',
    imageReviewPrompt: 'Please review this image and give diabetes prevention advice.',
    fallbackError: 'The chatbot could not reply right now. Please try again.',
    promptPlaceholder: 'Ask about meals, habits, or an image...',
    imageAttached: 'Image attached',
    imageReady: 'Ready for Ribbon to review.',
    attach: 'Attach',
    typing: 'Ribbon is preparing a response...',
    quickPrompts: ['Suggest breakfast', 'Suggest lunch', 'Suggest dinner', 'Healthy snack ideas'],
  },
  log: {
    title: 'Daily Log',
    subtitle: 'History for Ribbon and your own review.',
    noLogs: 'No logs yet',
    emptyHelp: "Tap Log your day to add today's health snapshot.",
    logYourDay: 'Log your day',
    glucose: 'Glucose',
    activity: 'Activity',
    sleep: 'Sleep',
    water: 'Water',
    balancedMeals: 'Balanced meals',
    mood: 'Mood',
    notesPlaceholder: 'Meals, cravings, exercise, symptoms...',
    saveLog: 'Save Log',
    noGlucose: 'No glucose',
    noSleep: 'No sleep',
    moods: { steady: 'Steady', good: 'Good', tired: 'Tired', stressed: 'Stressed' },
  },
  guide: {
    title: 'Guide',
    subtitle: 'Simple food and lifestyle targets for lowering diabetes risk.',
    eatTitle: 'What to Eat',
    mealIdeas: [
      'Breakfast: oats with berries, plain yogurt, and nuts.',
      'Lunch: grilled chicken or beans with salad and brown rice.',
      'Dinner: fish, lentils, or tofu with vegetables and a small whole grain portion.',
      'Snack: apple slices, boiled eggs, hummus with carrots, or unsalted nuts.',
    ],
    doTitle: 'What to Do',
    habitIdeas: [
      'Walk for 10 to 20 minutes after meals when possible.',
      'Keep water nearby and avoid buying sugary drinks for home.',
      'Sleep 7 to 9 hours because poor sleep can raise cravings and glucose levels.',
      'Check weight, activity, and glucose trends weekly instead of judging one day.',
    ],
    modelTitle: 'About the Model',
    modelBody:
      'Diabeto uses a lightweight local scoring model based on common risk factors: age, BMI, glucose, family history, activity level, and sugary drink intake.',
    modelFuture:
      'A future version can connect this screen to a trained Python or cloud AI model after you collect a real dataset and decide where predictions should run.',
  },
  predict: {
    subtitle: 'AI-style diabetes risk prediction and habit advice.',
    yourDetails: 'Your Details',
    canMeasureGlucose: 'Can measure glucose now?',
    prediction: 'Prediction',
    bmi: 'BMI',
    personalAdvice: 'Personal advice',
    enterValid: 'Enter valid numbers to see your prediction.',
    disclaimer: 'This app is for education only and does not diagnose diabetes.',
    riskLevels: { Low: 'Low', Moderate: 'Moderate', High: 'High' },
  },
};

const ar: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'رجوع',
    cancel: 'إلغاء',
    clear: 'مسح',
    continue: 'متابعة',
    no: 'لا',
    optional: 'اختياري',
    paste: 'لصق',
    remove: 'إزالة',
    save: 'حفظ',
    send: 'إرسال',
    wait: 'انتظر',
    yes: 'نعم',
  },
  tabs: {
    chat: 'الدردشة',
    guide: 'الدليل',
    home: 'الرئيسية',
    log: 'السجل',
    predict: 'التنبؤ',
    settings: 'الإعدادات',
  },
  home: {
    subtitle: 'تابع مستوى الخطورة، وافهم الوجبات، وتحدث عن خيارات صحية أفضل.',
    today: 'اليوم',
    quickRiskCheck: 'ابدأ بفحص سريع لمستوى الخطورة.',
    predictionHelps: 'تساعد بيانات التنبؤ Ribbon على تقديم نصائح غذائية وعادات أكثر دقة.',
    openPredict: 'افتح التنبؤ',
    guideBody: 'أفكار وجبات متوازنة وأهداف عادات بسيطة.',
    dailyLog: 'السجل اليومي',
    dailyLogBody: 'سجل الجلوكوز والنوم والنشاط والماء والوجبات والملاحظات.',
    chatBody: 'اسأل Ribbon عن الوجبات والوجبات الخفيفة والعادات أو صور الطعام.',
    settingsBody: 'عدّل المظهر واللغة والألوان ونبرة Ribbon.',
    disclaimer: 'Diabeto للتثقيف فقط ولا يستبدل التشخيص أو الرعاية الطبية.',
  },
  onboarding: {
    pageTitles: ['الترحيب', 'الشروط', 'بيانات الصحة', 'قياس الجلوكوز', 'Ribbon'],
    startDiabeto: 'ابدأ Diabeto',
    welcomeSubtitle:
      'مساعد للوقاية من السكري يقدر مستوى الخطورة ويقدم نصائح عادات عملية من بيانات صحية بسيطة.',
    welcomeItems: [
      'تقدير سريع للخطورة بناء على نمط الحياة',
      'نصائح شخصية من بياناتك',
      'دردشة اختيارية بالذكاء الاصطناعي للوجبات وصور الطعام',
    ],
    beforeStart: 'قبل أن تبدأ',
    termsTitle: 'شروط الخدمة',
    termsBody:
      'Diabeto مخصص للتثقيف ودعم الوقاية فقط. لا يشخص السكري ولا يستبدل الطبيب ولا يقدم رعاية طارئة.',
    termsResponsibility:
      'أنت مسؤول عن مراجعة القرارات الصحية المهمة مع مختص رعاية صحية مؤهل.',
    privacyTitle: 'سياسة الخصوصية',
    privacyBody:
      'يستخدم Diabeto البيانات التي تدخلها لتقدير الخطورة وتخصيص ردود المرافق الذكي. قد ترسل رسائل الدردشة والصور المحددة إلى Gemini API الذي تم إعداده.',
    privacyWarning:
      'لا ترفع مستندات طبية خاصة أو هويات أو صورا لا تريد معالجتها بواسطة مزود الذكاء الاصطناعي.',
    agreeTerms: 'أوافق على شروط الخدمة',
    understandPrivacy: 'أفهم سياسة الخصوصية',
    yourDetails: 'بياناتك',
    detailsHelp: 'تساعد هذه البيانات Diabeto على إنشاء تقدير أولي. يمكنك تعديلها لاحقا.',
    age: 'العمر',
    height: 'الطول',
    weight: 'الوزن',
    years: 'سنة',
    activity: 'النشاط',
    low: 'منخفض',
    moderate: 'متوسط',
    high: 'مرتفع',
    sugaryDrinks: 'المشروبات السكرية',
    rarely: 'نادرا',
    sometimes: 'أحيانا',
    often: 'غالبا',
    familyHistory: 'تاريخ عائلي للسكري',
    glucoseAccess: 'قياس الجلوكوز',
    glucoseHelp: 'ليس كل شخص يستطيع قياس سكر الدم في المنزل. لن يطلب Diabeto قيمة الجلوكوز.',
    canMeasureGlucose: 'هل تستطيع قياس سكر الدم الآن؟',
    glucose: 'الجلوكوز',
    whatThisMeans: 'ماذا يعني ذلك',
    glucoseMeaning:
      'إذا لم تستطع قياس الجلوكوز، يقدر Diabeto الخطورة باستخدام العمر ومؤشر كتلة الجسم والتاريخ العائلي والنشاط وعادات المشروبات السكرية. يمكن لفحص الجلوكوز أو A1C أن يجعل الصورة أوضح لاحقا.',
    meetRibbon: 'تعرف على Ribbon',
    ribbonBody:
      'Ribbon هو مرافقك الصحي في Diabeto. يمكنه مساعدتك على تحويل تقدير الخطورة إلى أفكار وجبات عملية وبدائل طعام وأهداف نشاط وعادات يومية أكثر أمانا.',
    ribbonItems: [
      'يستخدم بياناتك الصحية المحفوظة عند الدردشة',
      'يمكنه مراجعة صور الطعام أو الشراب التي ترفقها',
      'يتطلب مفتاح Gemini API الخاص بك من Google AI Studio',
      'الصق المفتاح في الإعدادات قبل استخدام الدردشة',
      'يحافظ على النصائح تعليمية وداعمة وعملية',
    ],
  },
  settings: {
    title: 'الإعدادات',
    subtitle: 'خصص Diabeto و Ribbon.',
    geminiApiKey: 'مفتاح Gemini API',
    keyHelp: 'يستخدم Ribbon مفتاح Google AI Studio الخاص بك. يبقى المفتاح على هذا الجهاز.',
    keyPlaceholder: 'الصق مفتاح Gemini API',
    getApiKey: 'احصل على مفتاح API',
    appearance: 'المظهر',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    colorTheme: 'سمة الألوان',
    colorThemeLabels: {
      sky: 'سماوي',
      mint: 'نعناعي',
      violet: 'بنفسجي',
      coral: 'مرجاني',
    },
    ribbonTone: 'نبرة Ribbon',
    ribbonToneLabels: {
      warm: 'دافئة',
      cold: 'مهنية',
      aggressive: 'حادة',
      casual: 'عفوية',
    },
    ribbonToneDescriptions: {
      warm: 'النبرة الافتراضية',
      cold: 'مختصرة ومحايدة ومباشرة',
      aggressive: 'تحذير: ستكون Ribbon قاسية جدا عند عرض أطعمة غير صحية.',
      casual: 'مصممة للمحادثات الخفيفة والعصرية',
    },
  },
  chat: {
    starter:
      'مرحبا، أنا Ribbon. أستطيع مساعدتك في تخطيط وجبات متوازنة وفهم اختيارات الطعام ومراجعة الصور وبناء عادات تقلل خطر السكري.',
    subtitle: 'مرافقك الصحي من Diabeto.',
    keyNeeded: 'مطلوب مفتاح Gemini API',
    usingAll: 'يستخدم بيانات التنبؤ والسجلات اليومية وذاكرة الدردشة',
    usingMemory: 'يستخدم ذاكرة الدردشة فقط',
    keyPanelTitle: 'يحتاج Ribbon إلى مفتاح Gemini API.',
    keyPanelBody: 'أنشئ مفتاحا في Google AI Studio، ثم انسخه والصقه في الإعدادات.',
    openSettings: 'افتح الإعدادات',
    attachImage: 'إرفاق صورة',
    attachImageMessage: 'اختر مصدر الصورة.',
    takePhoto: 'التقاط صورة',
    choosePhoto: 'اختيار صورة',
    photoAccessNeeded: 'يلزم الوصول إلى الصور قبل أن يتمكن Ribbon من مراجعة صورة من مكتبتك.',
    cameraAccessNeeded: 'يلزم الوصول إلى الكاميرا قبل أن يتمكن Ribbon من مراجعة صورة جديدة.',
    imageTooLarge: 'هذه الصورة كبيرة جدا. اختر صورة أصغر.',
    imageFailed: 'لم أتمكن من معالجة هذه الصورة. اختر صورة مختلفة.',
    addKeyBeforeChat: 'أضف مفتاح Gemini API في الإعدادات قبل الدردشة مع Ribbon.',
    imageReviewPrompt: 'يرجى مراجعة هذه الصورة وتقديم نصائح للوقاية من السكري.',
    fallbackError: 'لم يتمكن روبوت الدردشة من الرد الآن. حاول مرة أخرى.',
    promptPlaceholder: 'اسأل عن الوجبات أو العادات أو صورة...',
    imageAttached: 'تم إرفاق صورة',
    imageReady: 'جاهزة لمراجعة Ribbon.',
    attach: 'إرفاق',
    typing: 'Ribbon يجهز ردا...',
    quickPrompts: ['اقترح فطورا', 'اقترح غداء', 'اقترح عشاء', 'أفكار وجبات خفيفة صحية'],
  },
  log: {
    title: 'السجل اليومي',
    subtitle: 'تاريخ للمراجعة بواسطة Ribbon ولك أنت.',
    noLogs: 'لا توجد سجلات بعد',
    emptyHelp: 'اضغط سجل يومك لإضافة لقطة صحية لليوم.',
    logYourDay: 'سجل يومك',
    glucose: 'الجلوكوز',
    activity: 'النشاط',
    sleep: 'النوم',
    water: 'الماء',
    balancedMeals: 'الوجبات المتوازنة',
    mood: 'المزاج',
    notesPlaceholder: 'وجبات، رغبات، تمرين، أعراض...',
    saveLog: 'حفظ السجل',
    noGlucose: 'لا يوجد جلوكوز',
    noSleep: 'لا يوجد نوم',
    moods: { steady: 'مستقر', good: 'جيد', tired: 'متعب', stressed: 'متوتر' },
  },
  guide: {
    title: 'الدليل',
    subtitle: 'أهداف غذاء ونمط حياة بسيطة لتقليل خطر السكري.',
    eatTitle: 'ماذا تأكل',
    mealIdeas: [
      'الفطور: شوفان مع توت ولبن عادي ومكسرات.',
      'الغداء: دجاج مشوي أو فاصوليا مع سلطة وأرز بني.',
      'العشاء: سمك أو عدس أو توفو مع خضار وحصة صغيرة من الحبوب الكاملة.',
      'وجبة خفيفة: شرائح تفاح أو بيض مسلوق أو حمص مع جزر أو مكسرات غير مملحة.',
    ],
    doTitle: 'ماذا تفعل',
    habitIdeas: [
      'امش 10 إلى 20 دقيقة بعد الوجبات عندما يكون ذلك ممكنا.',
      'احتفظ بالماء قريبا وتجنب شراء المشروبات السكرية للمنزل.',
      'نم 7 إلى 9 ساعات لأن قلة النوم قد تزيد الرغبة في الطعام ومستوى الجلوكوز.',
      'راجع اتجاهات الوزن والنشاط والجلوكوز أسبوعيا بدلا من الحكم على يوم واحد.',
    ],
    modelTitle: 'عن النموذج',
    modelBody:
      'يستخدم Diabeto نموذج تسجيل محليا خفيفا يعتمد على عوامل خطورة شائعة: العمر ومؤشر كتلة الجسم والجلوكوز والتاريخ العائلي ومستوى النشاط وتناول المشروبات السكرية.',
    modelFuture:
      'يمكن لإصدار مستقبلي ربط هذه الشاشة بنموذج Python مدرب أو نموذج ذكاء اصطناعي سحابي بعد جمع مجموعة بيانات حقيقية وتحديد مكان تشغيل التنبؤات.',
  },
  predict: {
    subtitle: 'تنبؤ بأسلوب الذكاء الاصطناعي لمخاطر السكري ونصائح عادات.',
    yourDetails: 'بياناتك',
    canMeasureGlucose: 'هل تستطيع قياس الجلوكوز الآن؟',
    prediction: 'التنبؤ',
    bmi: 'مؤشر كتلة الجسم',
    personalAdvice: 'نصائح شخصية',
    enterValid: 'أدخل أرقاما صحيحة لرؤية التنبؤ.',
    disclaimer: 'هذا التطبيق للتثقيف فقط ولا يشخص السكري.',
    riskLevels: { Low: 'منخفض', Moderate: 'متوسط', High: 'مرتفع' },
  },
};

export const translations = { en, ar };

export function resolveLanguage(preference: AppLanguage): SupportedLanguage {
  if (preference !== 'system') {
    return preference;
  }

  const locale = getLocales()[0];
  return locale?.languageCode === 'ar' ? 'ar' : 'en';
}

export function useI18n() {
  const preferences = useAppPreferences();
  const language = resolveLanguage(preferences.language);

  return {
    isRtl: language === 'ar',
    language,
    text: translations[language],
  };
}
