import { getLocales } from 'expo-localization';

import { useAppPreferences, type AppLanguage } from '@/lib/app-preferences';

type SupportedLanguage = 'en' | 'ar' | 'es' | 'secret';

export const languageLabels: Record<AppLanguage, string> = {
  system: 'System',
  en: 'English',
  ar: 'العربية',
  es: 'Español',
  secret: 'meow',
};

const en = {
  common: {
    appName: 'Diabeto',
    back: 'Back',
    cancel: 'Cancel',
    clear: 'Clear',
    continue: 'Continue',
    no: 'No',
    optional: 'Optional',
    paste: 'Paste',
    remove: 'Remove',
    save: 'Save',
    send: 'Send',
    wait: 'Wait',
    yes: 'Yes',
  },
  tabs: {
    chat: 'Chat',
    guide: 'Guide',
    home: 'Home',
    log: 'Log',
    predict: 'Predict',
    settings: 'Settings',
  },
  home: {
    subtitle: 'Track risk, understand meals, and chat through healthier choices.',
    today: 'Today',
    quickRiskCheck: 'Start with a quick risk check.',
    predictionHelps: 'Your prediction data also helps Ribbon give more specific food and habit advice.',
    openPredict: 'Open Predict',
    guideBody: 'Balanced meal ideas and simple habit targets.',
    dailyLog: 'Daily Log',
    dailyLogBody: 'Record glucose, sleep, activity, water, meals, and notes.',
    chatBody: 'Ask Ribbon about meals, snacks, habits, or food photos.',
    settingsBody: 'Adjust appearance, language, and advanced options.',
    disclaimer: 'Diabeto is educational and does not replace medical diagnosis or care.',
    launchTip: "Today's Tip",
    menuTitle: 'Your Diabeto menu',
    tips: [
      'Pair carbs with protein or fiber to help keep blood sugar steadier.',
      'A 10-minute walk after a meal can support better glucose control.',
      'Keep water visible. It makes sugary drinks easier to skip.',
      'Sleep changes cravings and energy. Track it alongside meals.',
    ],
    metrics: {
      riskLabel: 'Risk',
      riskValue: 'Score',
      habitsLabel: 'Habits',
      habitsValue: 'Daily',
      coachLabel: 'Coach',
      coachValue: 'Ribbon',
    },
  },
  onboarding: {
    pageTitles: ['Welcome', 'Terms', 'Health Details', 'Glucose Access', 'Ribbon'],
    startDiabeto: 'Start Diabeto',
    welcomeSubtitle:
      'A diabetes prevention assistant that estimates risk and gives practical habit advice from simple health details.',
    welcomeItems: [
      'Quick lifestyle-based risk estimate',
      'Personal advice from your details',
      'Optional AI chat for meals and food images',
    ],
    beforeStart: 'Before You Start',
    termsTitle: 'Terms of Service',
    termsBody:
      'Diabeto is for education and prevention support only. It does not diagnose diabetes, replace a doctor, or provide emergency care.',
    termsResponsibility:
      'You are responsible for checking important health decisions with a qualified healthcare professional.',
    privacyTitle: 'Privacy Policy',
    privacyBody:
      "Diabeto uses the details you enter to estimate risk and personalize the AI companion's replies. Chat messages and selected images may be sent to the configured Gemini API.",
    privacyWarning:
      'Do not upload private medical documents, IDs, or photos you do not want processed by the AI provider.',
    agreeTerms: 'I agree to the Terms of Service',
    understandPrivacy: 'I understand the Privacy Policy',
    yourDetails: 'Your Details',
    detailsHelp: 'These details help Diabeto make a first estimate. You can adjust them later.',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    years: 'years',
    activity: 'Activity',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    sugaryDrinks: 'Sugary drinks',
    rarely: 'Rarely',
    sometimes: 'Sometimes',
    often: 'Often',
    familyHistory: 'Family history of diabetes',
    glucoseAccess: 'Glucose Access',
    glucoseHelp: 'Not everyone can measure blood glucose at home. Diabeto will not require a glucose value.',
    canMeasureGlucose: 'Are you able to measure your blood glucose right now?',
    glucose: 'Glucose',
    whatThisMeans: 'What this means',
    glucoseMeaning:
      'If you cannot measure glucose, Diabeto estimates risk using age, BMI, family history, activity, and sugary drink habits. A lab glucose or A1C test can make the picture clearer later.',
    meetRibbon: 'Meet Ribbon',
    ribbonBody:
      'Ribbon is your Diabeto health companion. She can help you turn your risk estimate into practical meal ideas, food swaps, activity goals, and safer daily habits.',
    ribbonItems: [
      'Uses your saved health details when you chat',
      'Can review food or drink images you attach',
      'Requires your own Gemini API key from Google AI Studio',
      'Paste the key in Settings before using chat',
      'Keeps advice educational, supportive, and practical',
    ],
  },
  settings: {
    title: 'Settings',
    subtitle: 'Personalize Diabeto and Ribbon.',
    geminiApiKey: 'Gemini API Key',
    keyHelp: 'Ribbon uses your own Google AI Studio key. It stays on this device.',
    keyPlaceholder: 'Paste Gemini API key',
    getApiKey: 'Get an API key',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    account: 'Account',
    accountSignedOut: 'Sign in or create an account with Supabase.',
    accountSetupNeeded: 'Add Supabase environment variables to enable accounts.',
    credits: 'Credits',
    creditsSubtitle: 'People and tools behind Diabeto.',
    creditsItems: ['Design and development: Ty and Co', 'Built with Expo and React Native', 'Accounts powered by Supabase', 'Nearby care powered by Google Maps'],
    advanced: 'Advanced',
    ribbonTone: 'Ribbon Tone',
    ribbonToneLabels: {
      warm: 'Warm',
      cold: 'Cold',
      aggressive: 'Aggressive',
      casual: 'Casual',
    },
    ribbonToneDescriptions: {
      warm: 'Default',
      cold: 'also known as Professional',
      aggressive: 'WARNING: You will be heavily insulted if you show images of unhealthy food.',
      casual: 'specifically designed for our gen z users, wassup',
    },
  },
  account: {
    title: 'Account',
    subtitle: 'Sign in to sync Diabeto data with your Supabase account.',
    setupNeeded: 'Supabase setup needed',
    setupHelp:
      'Add `EXPO_PUBLIC_SUPABASE_URL` and `EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY` to `.env.local`, then restart Expo.',
    signedIn: 'Signed in',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signInWithGoogle: 'Sign in with Google',
    createAccount: 'Create account',
    email: 'Email',
    password: 'Password',
    goBack: 'Go back',
    invalidCredentials: 'Enter an email and a password with at least 6 characters.',
    confirmEmail: 'Check your email to confirm your account, then sign in.',
    accountCreated: 'Account created. You are signed in.',
    authFailed: 'Authentication failed.',
    redirectingGoogle: 'Redirecting to Google...',
    googleFailed: 'Google sign-in failed.',
    signedOut: 'Signed out.',
    signOutFailed: 'Sign-out failed.',
    waitingGoogle: 'Waiting for Google sign-in...',
    loadingAccount: 'Loading your account...',
    onboardingTitle: 'Sign in to Diabeto',
    onboardingSubtitle: 'Sign in to restore saved data, create an account, or continue as guest.',
    restoringData: 'Restoring your Diabeto data...',
    restoreFailed: 'Could not restore your account data.',
    confirmEmailGuest: 'Check your email to confirm your account. You can continue setup as guest for now.',
    googleStartFailed: 'Could not start Google sign-in.',
    supabaseGuest: 'Supabase is not configured for this build. You can continue as guest.',
    continueAsGuest: 'Continue as guest',
  },
  chat: {
    starter:
      'Hi, I am Ribbon. I can help you plan balanced meals, understand food choices, review images, and build habits that lower diabetes risk.',
    subtitle: 'Your Diabeto health companion.',
    keyNeeded: 'Gemini API key needed',
    usingAll: 'Using Predict data, daily logs, and chat memory',
    usingMemory: 'Using chat memory only',
    keyPanelTitle: 'Ribbon needs your Gemini API key.',
    keyPanelBody: 'Create a key in Google AI Studio, copy it, then paste it in Settings.',
    openSettings: 'Open Settings',
    attachImage: 'Attach image',
    attachImageMessage: 'Choose where the image should come from.',
    takePhoto: 'Take photo',
    choosePhoto: 'Choose photo',
    photoAccessNeeded: 'Photo access is needed before Ribbon can review an image from your library.',
    cameraAccessNeeded: 'Camera access is needed before Ribbon can review a new photo.',
    imageTooLarge: 'That image is too large. Please choose a smaller photo.',
    imageFailed: 'I could not process that image. Please choose a different photo.',
    addKeyBeforeChat: 'Add your Gemini API key in Settings before chatting with Ribbon.',
    imageReviewPrompt: 'Please review this image and give diabetes prevention advice.',
    fallbackError: 'The chatbot could not reply right now. Please try again.',
    promptPlaceholder: 'Ask about meals, habits, or an image...',
    imageAttached: 'Image attached',
    imageReady: 'Ready for Ribbon to review.',
    attach: 'Attach',
    typing: 'Ribbon is preparing a response...',
    quickPrompts: ['Suggest breakfast', 'Suggest lunch', 'Suggest dinner', 'Healthy snack ideas'],
  },
  log: {
    title: 'Daily Log',
    subtitle: 'History for Ribbon and your own review.',
    noLogs: 'No logs yet',
    emptyHelp: "Tap Log your day to add today's health snapshot.",
    logYourDay: 'Log your day',
    glucose: 'Glucose',
    activity: 'Activity',
    sleep: 'Sleep',
    water: 'Water',
    balancedMeals: 'Balanced meals',
    mood: 'Mood',
    notesPlaceholder: 'Meals, cravings, exercise, symptoms...',
    saveLog: 'Save Log',
    noGlucose: 'No glucose',
    noSleep: 'No sleep',
    streakTitle: (count: number) => `${count} day streak`,
    streakActive: 'Keep logging daily to build momentum.',
    streakEmpty: 'Log today to start a streak.',
    reminderSet: (time: string) => `Daily reminder set for ${time}.`,
    reminderOff: 'Daily reminder off.',
    reminderOn: 'Reminder on',
    remindMe: 'Remind me',
    reminderUnavailable: 'Daily reminders are available in the mobile app.',
    reminderPermissionDenied: 'Notification permission was not granted.',
    reminderChannel: 'Daily log reminders',
    reminderTitle: 'Log your Diabeto day',
    reminderBody: 'Add glucose, activity, sleep, water, and meals to keep your streak going.',
    reminderTime: 'Reminder time',
    reminderTimeHelp: 'Adjusts in 15-minute steps.',
    hours: 'hours',
    cups: 'cups',
    meals: 'meals',
    moods: { steady: 'Steady', good: 'Good', tired: 'Tired', stressed: 'Stressed' },
  },
  guide: {
    title: 'Guide',
    subtitle: 'Simple food and lifestyle targets for lowering diabetes risk.',
    eatTitle: 'What to Eat',
    mealIdeas: [
      'Breakfast: oats with berries, plain yogurt, and nuts.',
      'Lunch: grilled chicken or beans with salad and brown rice.',
      'Dinner: fish, lentils, or tofu with vegetables and a small whole grain portion.',
      'Snack: apple slices, boiled eggs, hummus with carrots, or unsalted nuts.',
    ],
    doTitle: 'What to Do',
    habitIdeas: [
      'Walk for 10 to 20 minutes after meals when possible.',
      'Keep water nearby and avoid buying sugary drinks for home.',
      'Sleep 7 to 9 hours because poor sleep can raise cravings and glucose levels.',
      'Check weight, activity, and glucose trends weekly instead of judging one day.',
    ],
    modelTitle: 'About the Model',
    modelBody:
      'Diabeto uses a lightweight local scoring model based on common risk factors: age, BMI, glucose, family history, activity level, and sugary drink intake.',
    modelFuture:
      'A future version can connect this screen to a trained Python or cloud AI model after you collect a real dataset and decide where predictions should run.',
  },
  predict: {
    subtitle: 'AI-style diabetes risk prediction and habit advice.',
    yourDetails: 'Your Details',
    canMeasureGlucose: 'Can measure glucose now?',
    prediction: 'Prediction',
    bmi: 'BMI',
    personalAdvice: 'Personal advice',
    enterValid: 'Enter valid numbers to see your prediction.',
    disclaimer: 'This app is for education only and does not diagnose diabetes.',
    riskLevels: { Low: 'Low', Moderate: 'Moderate', High: 'High' },
  },
};

const es: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'Atrás',
    cancel: 'Cancelar',
    clear: 'Borrar',
    continue: 'Continuar',
    no: 'No',
    optional: 'Opcional',
    paste: 'Pegar',
    remove: 'Quitar',
    save: 'Guardar',
    send: 'Enviar',
    wait: 'Espera',
    yes: 'Sí',
  },
  tabs: {
    chat: 'Chat',
    guide: 'Guía',
    home: 'Inicio',
    log: 'Registro',
    predict: 'Predicción',
    settings: 'Ajustes',
  },
  home: {
    subtitle: 'Controla el riesgo, entiende tus comidas y conversa sobre mejores decisiones de salud.',
    today: 'Hoy',
    quickRiskCheck: 'Empieza con una revisión rápida del riesgo.',
    predictionHelps: 'Tus datos de predicción también ayudan a Ribbon a dar consejos más específicos sobre comida y hábitos.',
    openPredict: 'Abrir predicción',
    guideBody: 'Ideas de comidas equilibradas y objetivos de hábitos simples.',
    dailyLog: 'Registro diario',
    dailyLogBody: 'Registra glucosa, sueño, actividad, agua, comidas y notas.',
    chatBody: 'Pregunta a Ribbon sobre comidas, snacks, hábitos o fotos de alimentos.',
    settingsBody: 'Ajusta apariencia, idioma y opciones avanzadas.',
    disclaimer: 'Diabeto es educativo y no sustituye el diagnóstico ni la atención médica.',
    launchTip: 'Consejo de hoy',
    menuTitle: 'Tu menú de Diabeto',
    tips: [
      'Combina carbohidratos con proteína o fibra para ayudar a estabilizar la glucosa.',
      'Caminar 10 minutos después de comer puede apoyar el control de glucosa.',
      'Mantén agua a la vista. Ayuda a evitar bebidas azucaradas.',
      'El sueño cambia los antojos y la energía. Regístralo junto con tus comidas.',
    ],
    metrics: {
      riskLabel: 'Riesgo',
      riskValue: 'Puntaje',
      habitsLabel: 'Habitos',
      habitsValue: 'Diario',
      coachLabel: 'Guia',
      coachValue: 'Ribbon',
    },
  },
  onboarding: {
    pageTitles: ['Bienvenida', 'Términos', 'Datos de salud', 'Acceso a glucosa', 'Ribbon'],
    startDiabeto: 'Empezar Diabeto',
    welcomeSubtitle:
      'Un asistente de prevención de diabetes que estima el riesgo y da consejos prácticos de hábitos a partir de datos de salud simples.',
    welcomeItems: [
      'Estimación rápida del riesgo basada en estilo de vida',
      'Consejos personales según tus datos',
      'Chat opcional con IA para comidas e imágenes de alimentos',
    ],
    beforeStart: 'Antes de empezar',
    termsTitle: 'Términos de servicio',
    termsBody:
      'Diabeto es solo para educación y apoyo en prevención. No diagnostica diabetes, no reemplaza a un médico ni ofrece atención de emergencia.',
    termsResponsibility:
      'Eres responsable de revisar las decisiones importantes de salud con un profesional sanitario cualificado.',
    privacyTitle: 'Política de privacidad',
    privacyBody:
      'Diabeto usa los datos que introduces para estimar el riesgo y personalizar las respuestas del asistente de IA. Los mensajes de chat y las imágenes seleccionadas pueden enviarse a la API de Gemini configurada.',
    privacyWarning:
      'No subas documentos médicos privados, identificaciones ni fotos que no quieras que procese el proveedor de IA.',
    agreeTerms: 'Acepto los Términos de servicio',
    understandPrivacy: 'Entiendo la Política de privacidad',
    yourDetails: 'Tus datos',
    detailsHelp: 'Estos datos ayudan a Diabeto a hacer una primera estimación. Puedes ajustarlos después.',
    age: 'Edad',
    height: 'Altura',
    weight: 'Peso',
    years: 'años',
    activity: 'Actividad',
    low: 'Baja',
    moderate: 'Moderada',
    high: 'Alta',
    sugaryDrinks: 'Bebidas azucaradas',
    rarely: 'Rara vez',
    sometimes: 'A veces',
    often: 'A menudo',
    familyHistory: 'Antecedentes familiares de diabetes',
    glucoseAccess: 'Acceso a glucosa',
    glucoseHelp: 'No todo el mundo puede medir la glucosa en casa. Diabeto no exige un valor de glucosa.',
    canMeasureGlucose: '¿Puedes medir tu glucosa en sangre ahora?',
    glucose: 'Glucosa',
    whatThisMeans: 'Qué significa esto',
    glucoseMeaning:
      'Si no puedes medir la glucosa, Diabeto estima el riesgo usando edad, IMC, antecedentes familiares, actividad y hábitos de bebidas azucaradas. Una prueba de glucosa o A1C puede aclarar mejor el panorama más adelante.',
    meetRibbon: 'Conoce a Ribbon',
    ribbonBody:
      'Ribbon es tu acompañante de salud en Diabeto. Puede ayudarte a convertir tu estimación de riesgo en ideas prácticas de comidas, cambios de alimentos, objetivos de actividad y hábitos diarios más seguros.',
    ribbonItems: [
      'Usa tus datos de salud guardados cuando chateas',
      'Puede revisar imágenes de comida o bebida que adjuntes',
      'Requiere tu propia clave de Gemini API de Google AI Studio',
      'Pega la clave en Ajustes antes de usar el chat',
      'Mantiene los consejos educativos, útiles y prácticos',
    ],
  },
  settings: {
    title: 'Ajustes',
    subtitle: 'Personaliza Diabeto y Ribbon.',
    geminiApiKey: 'Clave de Gemini API',
    keyHelp: 'Ribbon usa tu propia clave de Google AI Studio. Permanece en este dispositivo.',
    keyPlaceholder: 'Pega la clave de Gemini API',
    getApiKey: 'Obtener una clave API',
    appearance: 'Apariencia',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    language: 'Idioma',
    account: 'Cuenta',
    accountSignedOut: 'Inicia sesion o crea una cuenta con Supabase.',
    accountSetupNeeded: 'Anade las variables de entorno de Supabase para activar cuentas.',
    credits: 'Creditos',
    creditsSubtitle: 'Personas y herramientas detras de Diabeto.',
    creditsItems: ['Diseno y desarrollo: Ty and Co', 'Creado con Expo y React Native', 'Cuentas con Supabase', 'Atencion cercana con Google Maps'],
    advanced: 'Avanzado',
    ribbonTone: 'Tono de Ribbon',
    ribbonToneLabels: {
      warm: 'Cálido',
      cold: 'Profesional',
      aggressive: 'Agresivo',
      casual: 'Casual',
    },
    ribbonToneDescriptions: {
      warm: 'Predeterminado',
      cold: 'conciso, neutral y directo',
      aggressive: 'ADVERTENCIA: Ribbon será muy dura si muestras comida poco saludable.',
      casual: 'diseñado para conversaciones relajadas y actuales',
    },
  },
  account: {
    title: 'Cuenta',
    subtitle: 'Inicia sesion para sincronizar los datos de Diabeto con tu cuenta de Supabase.',
    setupNeeded: 'Se necesita configurar Supabase',
    setupHelp:
      'Anade `EXPO_PUBLIC_SUPABASE_URL` y `EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY` a `.env.local`, luego reinicia Expo.',
    signedIn: 'Sesion iniciada',
    signIn: 'Iniciar sesion',
    signOut: 'Cerrar sesion',
    signInWithGoogle: 'Iniciar sesion con Google',
    createAccount: 'Crear cuenta',
    email: 'Email',
    password: 'Contrasena',
    goBack: 'Volver',
    invalidCredentials: 'Introduce un email y una contrasena de al menos 6 caracteres.',
    confirmEmail: 'Revisa tu email para confirmar la cuenta y luego inicia sesion.',
    accountCreated: 'Cuenta creada. Has iniciado sesion.',
    authFailed: 'Error de autenticacion.',
    redirectingGoogle: 'Redirigiendo a Google...',
    googleFailed: 'Error al iniciar sesion con Google.',
    signedOut: 'Sesion cerrada.',
    signOutFailed: 'Error al cerrar sesion.',
    waitingGoogle: 'Esperando el inicio de sesion con Google...',
    loadingAccount: 'Cargando tu cuenta...',
    onboardingTitle: 'Inicia sesion en Diabeto',
    onboardingSubtitle: 'Inicia sesion para restaurar datos, crear una cuenta o continuar como invitado.',
    restoringData: 'Restaurando tus datos de Diabeto...',
    restoreFailed: 'No se pudieron restaurar los datos de tu cuenta.',
    confirmEmailGuest: 'Revisa tu email para confirmar la cuenta. Puedes continuar como invitado por ahora.',
    googleStartFailed: 'No se pudo iniciar sesion con Google.',
    supabaseGuest: 'Supabase no esta configurado para esta version. Puedes continuar como invitado.',
    continueAsGuest: 'Continuar como invitado',
  },  chat: {
    starter:
      'Hola, soy Ribbon. Puedo ayudarte a planificar comidas equilibradas, entender elecciones de alimentos, revisar imágenes y crear hábitos que reduzcan el riesgo de diabetes.',
    subtitle: 'Tu acompañante de salud de Diabeto.',
    keyNeeded: 'Se necesita una clave de Gemini API',
    usingAll: 'Usando datos de Predicción, registros diarios y memoria del chat',
    usingMemory: 'Usando solo la memoria del chat',
    keyPanelTitle: 'Ribbon necesita tu clave de Gemini API.',
    keyPanelBody: 'Crea una clave en Google AI Studio, cópiala y pégala en Ajustes.',
    openSettings: 'Abrir Ajustes',
    attachImage: 'Adjuntar imagen',
    attachImageMessage: 'Elige de dónde debe venir la imagen.',
    takePhoto: 'Tomar foto',
    choosePhoto: 'Elegir foto',
    photoAccessNeeded: 'Se necesita acceso a fotos para que Ribbon pueda revisar una imagen de tu biblioteca.',
    cameraAccessNeeded: 'Se necesita acceso a la cámara para que Ribbon pueda revisar una foto nueva.',
    imageTooLarge: 'Esa imagen es demasiado grande. Elige una foto más pequeña.',
    imageFailed: 'No pude procesar esa imagen. Elige otra foto.',
    addKeyBeforeChat: 'Añade tu clave de Gemini API en Ajustes antes de chatear con Ribbon.',
    imageReviewPrompt: 'Revisa esta imagen y da consejos de prevención de diabetes.',
    fallbackError: 'El chatbot no pudo responder ahora. Inténtalo de nuevo.',
    promptPlaceholder: 'Pregunta sobre comidas, hábitos o una imagen...',
    imageAttached: 'Imagen adjunta',
    imageReady: 'Lista para que Ribbon la revise.',
    attach: 'Adjuntar',
    typing: 'Ribbon está preparando una respuesta...',
    quickPrompts: ['Sugerir desayuno', 'Sugerir almuerzo', 'Sugerir cena', 'Ideas de snacks saludables'],
  },
  log: {
    title: 'Registro diario',
    subtitle: 'Historial para Ribbon y para tu propia revisión.',
    noLogs: 'Aún no hay registros',
    emptyHelp: 'Toca Registrar tu día para añadir la instantánea de salud de hoy.',
    logYourDay: 'Registrar tu día',
    glucose: 'Glucosa',
    activity: 'Actividad',
    sleep: 'Sueño',
    water: 'Agua',
    balancedMeals: 'Comidas equilibradas',
    mood: 'Ánimo',
    notesPlaceholder: 'Comidas, antojos, ejercicio, síntomas...',
    saveLog: 'Guardar registro',
    noGlucose: 'Sin glucosa',
    noSleep: 'Sin sueño',
    streakTitle: (count: number) => `Racha de ${count} dia${count === 1 ? '' : 's'}`,
    streakActive: 'Sigue registrando cada dia para mantener el impulso.',
    streakEmpty: 'Registra hoy para empezar una racha.',
    reminderSet: (time: string) => `Recordatorio diario configurado para ${time}.`,
    reminderOff: 'Recordatorio diario desactivado.',
    reminderOn: 'Recordatorio activo',
    remindMe: 'Recordarme',
    reminderUnavailable: 'Los recordatorios diarios están disponibles en la app móvil.',
    reminderPermissionDenied: 'No se concedió el permiso de notificaciones.',
    reminderChannel: 'Recordatorios del registro diario',
    reminderTitle: 'Registra tu día en Diabeto',
    reminderBody: 'Añade glucosa, actividad, sueño, agua y comidas para mantener tu racha.',
    reminderTime: 'Hora del recordatorio',
    reminderTimeHelp: 'Se ajusta en pasos de 15 minutos.',
    hours: 'horas',
    cups: 'vasos',
    meals: 'comidas',
    moods: { steady: 'Estable', good: 'Bien', tired: 'Cansado', stressed: 'Estresado' },
  },
  guide: {
    title: 'Guía',
    subtitle: 'Objetivos simples de alimentación y estilo de vida para reducir el riesgo de diabetes.',
    eatTitle: 'Qué comer',
    mealIdeas: [
      'Desayuno: avena con frutos rojos, yogur natural y frutos secos.',
      'Almuerzo: pollo a la plancha o frijoles con ensalada y arroz integral.',
      'Cena: pescado, lentejas o tofu con verduras y una porción pequeña de cereal integral.',
      'Snack: rodajas de manzana, huevos cocidos, hummus con zanahorias o frutos secos sin sal.',
    ],
    doTitle: 'Qué hacer',
    habitIdeas: [
      'Camina de 10 a 20 minutos después de las comidas cuando sea posible.',
      'Ten agua cerca y evita comprar bebidas azucaradas para casa.',
      'Duerme de 7 a 9 horas porque dormir mal puede aumentar antojos y niveles de glucosa.',
      'Revisa tendencias de peso, actividad y glucosa cada semana en vez de juzgar un solo día.',
    ],
    modelTitle: 'Sobre el modelo',
    modelBody:
      'Diabeto usa un modelo local ligero de puntuación basado en factores de riesgo comunes: edad, IMC, glucosa, antecedentes familiares, nivel de actividad y consumo de bebidas azucaradas.',
    modelFuture:
      'Una versión futura puede conectar esta pantalla a un modelo Python entrenado o a un modelo de IA en la nube cuando tengas un conjunto de datos real y decidas dónde deben ejecutarse las predicciones.',
  },
  predict: {
    subtitle: 'Predicción de riesgo de diabetes estilo IA y consejos de hábitos.',
    yourDetails: 'Tus datos',
    canMeasureGlucose: '¿Puedes medir glucosa ahora?',
    prediction: 'Predicción',
    bmi: 'IMC',
    personalAdvice: 'Consejos personales',
    enterValid: 'Introduce números válidos para ver tu predicción.',
    disclaimer: 'Esta app es solo educativa y no diagnostica diabetes.',
    riskLevels: { Low: 'Bajo', Moderate: 'Moderado', High: 'Alto' },
  },
};

const secret: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'mrrp mrrp',
    cancel: 'hiss mrrp',
    clear: 'hiss hiss',
    continue: 'meow meow',
    no: 'hiss',
    optional: 'mew?',
    paste: 'mrrp meow',
    remove: 'hiss mew',
    save: 'purr purr',
    send: 'meow!',
    wait: 'purr...',
    yes: 'meow',
  },
  tabs: {
    chat: 'mrrp',
    guide: 'purr',
    home: 'meow',
    log: 'mew',
    predict: 'hiss?',
    settings: 'prrr',
  },
  home: {
    subtitle: 'meow purr mrrp mew.',
    today: 'meow',
    quickRiskCheck: 'hiss? mew mew.',
    predictionHelps: 'hiss? mew. mrrp purr.',
    openPredict: 'hiss? meow',
    guideBody: 'purr meow mew.',
    dailyLog: 'mew mew',
    dailyLogBody: 'mew purr meow mrrp.',
    chatBody: 'mrrp meow purr.',
    settingsBody: 'prrr meow purr.',
    disclaimer: 'purr hiss mew.',
    launchTip: 'today mew',
    menuTitle: 'Diabeto mew',
    tips: ['mew purr protein.', 'mrrp 10 after meow.', 'mew water.', 'purr sleep mew.'],
    metrics: {
      riskLabel: 'hiss?',
      riskValue: 'mew',
      habitsLabel: 'purr',
      habitsValue: 'meow',
      coachLabel: 'mrrp',
      coachValue: 'Ribbon',
    },
  },
  onboarding: {
    pageTitles: ['meow', 'hiss', 'mew mew', 'hiss?', 'mrrp'],
    startDiabeto: 'Diabeto meow',
    welcomeSubtitle: 'meow purr hiss? mrrp mew.',
    welcomeItems: ['hiss? mew', 'purr meow', 'mrrp meow'],
    beforeStart: 'mrrp mew',
    termsTitle: 'hiss purr',
    termsBody: 'purr hiss mew. hiss hiss.',
    termsResponsibility: 'mrrp purr mew.',
    privacyTitle: 'purr hiss',
    privacyBody: 'mew mrrp purr. hiss mew.',
    privacyWarning: 'hiss hiss mrrrow.',
    agreeTerms: 'meow hiss purr',
    understandPrivacy: 'meow purr hiss',
    yourDetails: 'mew mew',
    detailsHelp: 'mew mew hiss? purr.',
    age: 'mew',
    height: 'mrrrow',
    weight: 'purr',
    years: 'mew',
    activity: 'mrrp mrrp',
    low: 'purr',
    moderate: 'mrrp',
    high: 'hiss',
    sugaryDrinks: 'hiss meow',
    rarely: 'purr purr',
    sometimes: 'mrrp purr',
    often: 'hiss hiss',
    familyHistory: 'mew mrrp',
    glucoseAccess: 'hiss? mew',
    glucoseHelp: 'hiss? mew. mrrp purr.',
    canMeasureGlucose: 'hiss? mew?',
    glucose: 'hiss?',
    whatThisMeans: 'mrrp?',
    glucoseMeaning: 'hiss? mew. mew mrrp purr.',
    meetRibbon: 'mrrp meow',
    ribbonBody: 'mrrp purr meow hiss? mew.',
    ribbonItems: [
      'mew mew mrrp',
      'meow hiss? purr',
      'mrrp prrr mew',
      'prrr mrrp meow',
      'purr purr meow',
    ],
  },
  settings: {
    title: 'prrr',
    subtitle: 'prrr meow purr.',
    geminiApiKey: 'mrrp prrr',
    keyHelp: 'mrrp prrr purr.',
    keyPlaceholder: 'mrrp prrr meow',
    getApiKey: 'prrr meow',
    appearance: 'purr mew',
    system: 'mrrp',
    light: 'meow',
    dark: 'mrrrow',
    language: 'mrrp meow',
    account: 'mew prrr',
    accountSignedOut: 'mrrp meow prrr.',
    accountSetupNeeded: 'hiss prrr mew.',
    credits: 'prrr mew',
    creditsSubtitle: 'prrr Diabeto.',
    creditsItems: ['Ty and Co', 'Expo mew React Native', 'Supabase prrr', 'Google Maps prrr'],
    advanced: 'hiss?',
    ribbonTone: 'mrrp purr',
    ribbonToneLabels: {
      warm: 'purr',
      cold: 'mew',
      aggressive: 'hiss',
      casual: 'meow',
    },
    ribbonToneDescriptions: {
      warm: 'purr purr',
      cold: 'mew mrrp',
      aggressive: 'hiss hiss',
      casual: 'meow mrrp',
    },
  },
  account: {
    title: 'mew prrr',
    subtitle: 'mrrp Diabeto mew Supabase.',
    setupNeeded: 'Supabase hiss?',
    setupHelp: 'mrrp EXPO_PUBLIC_SUPABASE_URL mew EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY.',
    signedIn: 'mrrp meow',
    signIn: 'mrrp',
    signOut: 'hiss',
    signInWithGoogle: 'mrrp Google',
    createAccount: 'mew prrr',
    email: 'mew@',
    password: 'prrr',
    goBack: 'mrrp mrrp',
    invalidCredentials: 'mew@ prrr 6.',
    confirmEmail: 'mew@ purr, mrrp.',
    accountCreated: 'prrr meow.',
    authFailed: 'hiss prrr.',
    redirectingGoogle: 'Google mrrp...',
    googleFailed: 'Google hiss.',
    signedOut: 'hiss meow.',
    signOutFailed: 'hiss hiss.',
    waitingGoogle: 'Google purr...',
    loadingAccount: 'mew prrr...',
    onboardingTitle: 'mrrp Diabeto',
    onboardingSubtitle: 'mrrp mew, prrr, or purr.',
    restoringData: 'Diabeto mew purr...',
    restoreFailed: 'mew hiss.',
    confirmEmailGuest: 'mew@ purr. purr now.',
    googleStartFailed: 'Google mrrp hiss.',
    supabaseGuest: 'Supabase hiss. purr now.',
    continueAsGuest: 'purr now',
  },
  chat: {
    starter: 'mrrp! meow purr hiss? mew mrrp.',
    subtitle: 'mrrp purr.',
    keyNeeded: 'mrrp prrr?',
    usingAll: 'hiss? mew mrrp purr',
    usingMemory: 'mrrp mew',
    keyPanelTitle: 'mrrp prrr?',
    keyPanelBody: 'prrr mrrp meow.',
    openSettings: 'prrr meow',
    attachImage: 'meow hiss?',
    attachImageMessage: 'meow? mrrp?',
    takePhoto: 'meow!',
    choosePhoto: 'mew meow',
    photoAccessNeeded: 'hiss? meow mrrp.',
    cameraAccessNeeded: 'meow hiss? mrrp.',
    imageTooLarge: 'hiss hiss mrrrow.',
    imageFailed: 'hiss mew mrrp.',
    addKeyBeforeChat: 'mrrp prrr meow.',
    imageReviewPrompt: 'meow hiss? purr mrrp.',
    fallbackError: 'mrrrow mew hiss.',
    promptPlaceholder: 'mrrp meow...',
    imageAttached: 'meow hiss?',
    imageReady: 'mrrp purr.',
    attach: 'meow',
    typing: 'mrrp purr...',
    quickPrompts: ['meow purr', 'mew purr', 'mrrp purr', 'purr mew'],
  },
  log: {
    title: 'mew mew',
    subtitle: 'mew purr mrrp.',
    noLogs: 'mew? hiss',
    emptyHelp: 'mew meow.',
    logYourDay: 'mew meow',
    glucose: 'hiss?',
    activity: 'mrrp mrrp',
    sleep: 'purr',
    water: 'mew',
    balancedMeals: 'meow purr',
    mood: 'mrrp?',
    notesPlaceholder: 'meow, mrrp, purr...',
    saveLog: 'purr mew',
    noGlucose: 'hiss? hiss',
    noSleep: 'purr hiss',
    streakTitle: (count: number) => `${count} mew purr`,
    streakActive: 'mew meow purr.',
    streakEmpty: 'mew today purr.',
    reminderSet: (time: string) => `mew ${time}.`,
    reminderOff: 'mew hiss.',
    reminderOn: 'mew on',
    remindMe: 'mew me',
    reminderUnavailable: 'mew mobile.',
    reminderPermissionDenied: 'hiss permission.',
    reminderChannel: 'mew reminders',
    reminderTitle: 'mew Diabeto day',
    reminderBody: 'hiss? mrrp purr mew meow.',
    reminderTime: 'mew time',
    reminderTimeHelp: '15 mew.',
    hours: 'purr',
    cups: 'mew',
    meals: 'meow',
    moods: { steady: 'purr', good: 'meow', tired: 'mew', stressed: 'hiss' },
  },
  guide: {
    title: 'purr',
    subtitle: 'purr meow hiss? mew.',
    eatTitle: 'meow',
    mealIdeas: [
      'meow: purr mew mrrp.',
      'mew: meow purr mrrp.',
      'mrrp: purr meow mew.',
      'purr: mew meow purr.',
    ],
    doTitle: 'mrrp',
    habitIdeas: [
      'mrrp 10 20.',
      'mew mew. hiss hiss.',
      'purr 7 9.',
      'mew purr purr.',
    ],
    modelTitle: 'hiss?',
    modelBody: 'hiss? mew purr mrrp.',
    modelFuture: 'mrrp purr mew.',
  },
  predict: {
    subtitle: 'hiss? mew purr.',
    yourDetails: 'mew mew',
    canMeasureGlucose: 'hiss? mew?',
    prediction: 'hiss?',
    bmi: 'mrrrow',
    personalAdvice: 'purr meow',
    enterValid: 'mew 0 1 2 3.',
    disclaimer: 'purr hiss mew.',
    riskLevels: { Low: 'purr', Moderate: 'mrrp', High: 'hiss' },
  },
};

const ar: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'رجوع',
    cancel: 'إلغاء',
    clear: 'مسح',
    continue: 'متابعة',
    no: 'لا',
    optional: 'اختياري',
    paste: 'لصق',
    remove: 'إزالة',
    save: 'حفظ',
    send: 'إرسال',
    wait: 'انتظر',
    yes: 'نعم',
  },
  tabs: {
    chat: 'الدردشة',
    guide: 'الدليل',
    home: 'الرئيسية',
    log: 'السجل',
    predict: 'التنبؤ',
    settings: 'الإعدادات',
  },
  home: {
    subtitle: 'تابع مستوى الخطورة، وافهم الوجبات، وتحدث عن خيارات صحية أفضل.',
    today: 'اليوم',
    quickRiskCheck: 'ابدأ بفحص سريع لمستوى الخطورة.',
    predictionHelps: 'تساعد بيانات التنبؤ Ribbon على تقديم نصائح غذائية وعادات أكثر دقة.',
    openPredict: 'افتح التنبؤ',
    guideBody: 'أفكار وجبات متوازنة وأهداف عادات بسيطة.',
    dailyLog: 'السجل اليومي',
    dailyLogBody: 'سجل الجلوكوز والنوم والنشاط والماء والوجبات والملاحظات.',
    chatBody: 'اسأل Ribbon عن الوجبات والوجبات الخفيفة والعادات أو صور الطعام.',
    settingsBody: 'عدّل المظهر واللغة والخيارات المتقدمة.',
    disclaimer: 'Diabeto للتثقيف فقط ولا يستبدل التشخيص أو الرعاية الطبية.',
    launchTip: 'نصيحة اليوم',
    menuTitle: 'قائمة Diabeto',
    tips: [
      'اجمع الكربوهيدرات مع البروتين أو الألياف للمساعدة في ثبات سكر الدم.',
      'المشي 10 دقائق بعد الوجبة يمكن أن يدعم التحكم في الجلوكوز.',
      'اجعل الماء أمامك. هذا يسهل تجنب المشروبات السكرية.',
      'النوم يؤثر في الشهية والطاقة. سجله مع الوجبات.',
    ],
    metrics: {
      riskLabel: 'الخطر',
      riskValue: 'الدرجة',
      habitsLabel: 'العادات',
      habitsValue: 'يومي',
      coachLabel: 'المرافق',
      coachValue: 'Ribbon',
    },
  },
  onboarding: {
    pageTitles: ['الترحيب', 'الشروط', 'بيانات الصحة', 'قياس الجلوكوز', 'Ribbon'],
    startDiabeto: 'ابدأ Diabeto',
    welcomeSubtitle:
      'مساعد للوقاية من السكري يقدر مستوى الخطورة ويقدم نصائح عادات عملية من بيانات صحية بسيطة.',
    welcomeItems: [
      'تقدير سريع للخطورة بناء على نمط الحياة',
      'نصائح شخصية من بياناتك',
      'دردشة اختيارية بالذكاء الاصطناعي للوجبات وصور الطعام',
    ],
    beforeStart: 'قبل أن تبدأ',
    termsTitle: 'شروط الخدمة',
    termsBody:
      'Diabeto مخصص للتثقيف ودعم الوقاية فقط. لا يشخص السكري ولا يستبدل الطبيب ولا يقدم رعاية طارئة.',
    termsResponsibility:
      'أنت مسؤول عن مراجعة القرارات الصحية المهمة مع مختص رعاية صحية مؤهل.',
    privacyTitle: 'سياسة الخصوصية',
    privacyBody:
      'يستخدم Diabeto البيانات التي تدخلها لتقدير الخطورة وتخصيص ردود المرافق الذكي. قد ترسل رسائل الدردشة والصور المحددة إلى Gemini API الذي تم إعداده.',
    privacyWarning:
      'لا ترفع مستندات طبية خاصة أو هويات أو صورا لا تريد معالجتها بواسطة مزود الذكاء الاصطناعي.',
    agreeTerms: 'أوافق على شروط الخدمة',
    understandPrivacy: 'أفهم سياسة الخصوصية',
    yourDetails: 'بياناتك',
    detailsHelp: 'تساعد هذه البيانات Diabeto على إنشاء تقدير أولي. يمكنك تعديلها لاحقا.',
    age: 'العمر',
    height: 'الطول',
    weight: 'الوزن',
    years: 'سنة',
    activity: 'النشاط',
    low: 'منخفض',
    moderate: 'متوسط',
    high: 'مرتفع',
    sugaryDrinks: 'المشروبات السكرية',
    rarely: 'نادرا',
    sometimes: 'أحيانا',
    often: 'غالبا',
    familyHistory: 'تاريخ عائلي للسكري',
    glucoseAccess: 'قياس الجلوكوز',
    glucoseHelp: 'ليس كل شخص يستطيع قياس سكر الدم في المنزل. لن يطلب Diabeto قيمة الجلوكوز.',
    canMeasureGlucose: 'هل تستطيع قياس سكر الدم الآن؟',
    glucose: 'الجلوكوز',
    whatThisMeans: 'ماذا يعني ذلك',
    glucoseMeaning:
      'إذا لم تستطع قياس الجلوكوز، يقدر Diabeto الخطورة باستخدام العمر ومؤشر كتلة الجسم والتاريخ العائلي والنشاط وعادات المشروبات السكرية. يمكن لفحص الجلوكوز أو A1C أن يجعل الصورة أوضح لاحقا.',
    meetRibbon: 'تعرف على Ribbon',
    ribbonBody:
      'Ribbon هو مرافقك الصحي في Diabeto. يمكنه مساعدتك على تحويل تقدير الخطورة إلى أفكار وجبات عملية وبدائل طعام وأهداف نشاط وعادات يومية أكثر أمانا.',
    ribbonItems: [
      'يستخدم بياناتك الصحية المحفوظة عند الدردشة',
      'يمكنه مراجعة صور الطعام أو الشراب التي ترفقها',
      'يتطلب مفتاح Gemini API الخاص بك من Google AI Studio',
      'الصق المفتاح في الإعدادات قبل استخدام الدردشة',
      'يحافظ على النصائح تعليمية وداعمة وعملية',
    ],
  },
  settings: {
    title: 'الإعدادات',
    subtitle: 'خصص Diabeto و Ribbon.',
    geminiApiKey: 'مفتاح Gemini API',
    keyHelp: 'يستخدم Ribbon مفتاح Google AI Studio الخاص بك. يبقى المفتاح على هذا الجهاز.',
    keyPlaceholder: 'الصق مفتاح Gemini API',
    getApiKey: 'احصل على مفتاح API',
    appearance: 'المظهر',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    account: 'الحساب',
    accountSignedOut: 'سجل الدخول أو أنشئ حسابا باستخدام Supabase.',
    accountSetupNeeded: 'أضف متغيرات بيئة Supabase لتفعيل الحسابات.',
    credits: 'الاعتمادات',
    creditsSubtitle: 'الأشخاص والأدوات وراء Diabeto.',
    creditsItems: ['التصميم والتطوير: Ty and Co', 'مبني باستخدام Expo و React Native', 'الحسابات مدعومة من Supabase', 'الرعاية القريبة مدعومة من Google Maps'],
    advanced: 'متقدم',
    ribbonTone: 'نبرة Ribbon',
    ribbonToneLabels: {
      warm: 'دافئة',
      cold: 'مهنية',
      aggressive: 'حادة',
      casual: 'عفوية',
    },
    ribbonToneDescriptions: {
      warm: 'النبرة الافتراضية',
      cold: 'مختصرة ومحايدة ومباشرة',
      aggressive: 'تحذير: ستكون Ribbon قاسية جدا عند عرض أطعمة غير صحية.',
      casual: 'مصممة للمحادثات الخفيفة والعصرية',
    },
  },
  account: {
    title: 'الحساب',
    subtitle: 'سجل الدخول لمزامنة بيانات Diabeto مع حساب Supabase.',
    setupNeeded: 'يلزم إعداد Supabase',
    setupHelp:
      'أضف `EXPO_PUBLIC_SUPABASE_URL` و `EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY` إلى `.env.local`، ثم أعد تشغيل Expo.',
    signedIn: 'تم تسجيل الدخول',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    signInWithGoogle: 'تسجيل الدخول باستخدام Google',
    createAccount: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    goBack: 'رجوع',
    invalidCredentials: 'أدخل بريدا إلكترونيا وكلمة مرور من 6 أحرف على الأقل.',
    confirmEmail: 'تحقق من بريدك الإلكتروني لتأكيد الحساب، ثم سجل الدخول.',
    accountCreated: 'تم إنشاء الحساب. أنت مسجل الدخول.',
    authFailed: 'فشلت المصادقة.',
    redirectingGoogle: 'جار التحويل إلى Google...',
    googleFailed: 'فشل تسجيل الدخول باستخدام Google.',
    signedOut: 'تم تسجيل الخروج.',
    signOutFailed: 'فشل تسجيل الخروج.',
    waitingGoogle: 'بانتظار تسجيل الدخول باستخدام Google...',
    loadingAccount: 'جار تحميل حسابك...',
    onboardingTitle: 'سجل الدخول إلى Diabeto',
    onboardingSubtitle: 'سجل الدخول لاستعادة البيانات المحفوظة أو إنشاء حساب أو المتابعة كضيف.',
    restoringData: 'جار استعادة بيانات Diabeto...',
    restoreFailed: 'تعذرت استعادة بيانات حسابك.',
    confirmEmailGuest: 'تحقق من بريدك الإلكتروني لتأكيد الحساب. يمكنك المتابعة كضيف الآن.',
    googleStartFailed: 'تعذر بدء تسجيل الدخول باستخدام Google.',
    supabaseGuest: 'لم يتم إعداد Supabase لهذا الإصدار. يمكنك المتابعة كضيف.',
    continueAsGuest: 'المتابعة كضيف',
  },
  chat: {
    starter:
      'مرحبا، أنا Ribbon. أستطيع مساعدتك في تخطيط وجبات متوازنة وفهم اختيارات الطعام ومراجعة الصور وبناء عادات تقلل خطر السكري.',
    subtitle: 'مرافقك الصحي من Diabeto.',
    keyNeeded: 'مطلوب مفتاح Gemini API',
    usingAll: 'يستخدم بيانات التنبؤ والسجلات اليومية وذاكرة الدردشة',
    usingMemory: 'يستخدم ذاكرة الدردشة فقط',
    keyPanelTitle: 'يحتاج Ribbon إلى مفتاح Gemini API.',
    keyPanelBody: 'أنشئ مفتاحا في Google AI Studio، ثم انسخه والصقه في الإعدادات.',
    openSettings: 'افتح الإعدادات',
    attachImage: 'إرفاق صورة',
    attachImageMessage: 'اختر مصدر الصورة.',
    takePhoto: 'التقاط صورة',
    choosePhoto: 'اختيار صورة',
    photoAccessNeeded: 'يلزم الوصول إلى الصور قبل أن يتمكن Ribbon من مراجعة صورة من مكتبتك.',
    cameraAccessNeeded: 'يلزم الوصول إلى الكاميرا قبل أن يتمكن Ribbon من مراجعة صورة جديدة.',
    imageTooLarge: 'هذه الصورة كبيرة جدا. اختر صورة أصغر.',
    imageFailed: 'لم أتمكن من معالجة هذه الصورة. اختر صورة مختلفة.',
    addKeyBeforeChat: 'أضف مفتاح Gemini API في الإعدادات قبل الدردشة مع Ribbon.',
    imageReviewPrompt: 'يرجى مراجعة هذه الصورة وتقديم نصائح للوقاية من السكري.',
    fallbackError: 'لم يتمكن روبوت الدردشة من الرد الآن. حاول مرة أخرى.',
    promptPlaceholder: 'اسأل عن الوجبات أو العادات أو صورة...',
    imageAttached: 'تم إرفاق صورة',
    imageReady: 'جاهزة لمراجعة Ribbon.',
    attach: 'إرفاق',
    typing: 'Ribbon يجهز ردا...',
    quickPrompts: ['اقترح فطورا', 'اقترح غداء', 'اقترح عشاء', 'أفكار وجبات خفيفة صحية'],
  },
  log: {
    title: 'السجل اليومي',
    subtitle: 'تاريخ للمراجعة بواسطة Ribbon ولك أنت.',
    noLogs: 'لا توجد سجلات بعد',
    emptyHelp: 'اضغط سجل يومك لإضافة لقطة صحية لليوم.',
    logYourDay: 'سجل يومك',
    glucose: 'الجلوكوز',
    activity: 'النشاط',
    sleep: 'النوم',
    water: 'الماء',
    balancedMeals: 'الوجبات المتوازنة',
    mood: 'المزاج',
    notesPlaceholder: 'وجبات، رغبات، تمرين، أعراض...',
    saveLog: 'حفظ السجل',
    noGlucose: 'لا يوجد جلوكوز',
    noSleep: 'لا يوجد نوم',
    streakTitle: (count: number) => `سلسلة ${count} يوم`,
    streakActive: 'استمر في التسجيل يوميا للحفاظ على الزخم.',
    streakEmpty: 'سجل اليوم لبدء سلسلة.',
    reminderSet: (time: string) => `تم ضبط التذكير اليومي على ${time}.`,
    reminderOff: 'تم إيقاف التذكير اليومي.',
    reminderOn: 'التذكير مفعل',
    remindMe: 'ذكرني',
    reminderUnavailable: 'التذكيرات اليومية متاحة في تطبيق الهاتف.',
    reminderPermissionDenied: 'لم يتم منح إذن الإشعارات.',
    reminderChannel: 'تذكيرات السجل اليومي',
    reminderTitle: 'سجل يومك في Diabeto',
    reminderBody: 'أضف الجلوكوز والنشاط والنوم والماء والوجبات للحفاظ على سلسلتك.',
    reminderTime: 'وقت التذكير',
    reminderTimeHelp: 'يتغير بخطوات 15 دقيقة.',
    hours: 'ساعات',
    cups: 'أكواب',
    meals: 'وجبات',
    moods: { steady: 'مستقر', good: 'جيد', tired: 'متعب', stressed: 'متوتر' },
  },
  guide: {
    title: 'الدليل',
    subtitle: 'أهداف غذاء ونمط حياة بسيطة لتقليل خطر السكري.',
    eatTitle: 'ماذا تأكل',
    mealIdeas: [
      'الفطور: شوفان مع توت ولبن عادي ومكسرات.',
      'الغداء: دجاج مشوي أو فاصوليا مع سلطة وأرز بني.',
      'العشاء: سمك أو عدس أو توفو مع خضار وحصة صغيرة من الحبوب الكاملة.',
      'وجبة خفيفة: شرائح تفاح أو بيض مسلوق أو حمص مع جزر أو مكسرات غير مملحة.',
    ],
    doTitle: 'ماذا تفعل',
    habitIdeas: [
      'امش 10 إلى 20 دقيقة بعد الوجبات عندما يكون ذلك ممكنا.',
      'احتفظ بالماء قريبا وتجنب شراء المشروبات السكرية للمنزل.',
      'نم 7 إلى 9 ساعات لأن قلة النوم قد تزيد الرغبة في الطعام ومستوى الجلوكوز.',
      'راجع اتجاهات الوزن والنشاط والجلوكوز أسبوعيا بدلا من الحكم على يوم واحد.',
    ],
    modelTitle: 'عن النموذج',
    modelBody:
      'يستخدم Diabeto نموذج تسجيل محليا خفيفا يعتمد على عوامل خطورة شائعة: العمر ومؤشر كتلة الجسم والجلوكوز والتاريخ العائلي ومستوى النشاط وتناول المشروبات السكرية.',
    modelFuture:
      'يمكن لإصدار مستقبلي ربط هذه الشاشة بنموذج Python مدرب أو نموذج ذكاء اصطناعي سحابي بعد جمع مجموعة بيانات حقيقية وتحديد مكان تشغيل التنبؤات.',
  },
  predict: {
    subtitle: 'تنبؤ بأسلوب الذكاء الاصطناعي لمخاطر السكري ونصائح عادات.',
    yourDetails: 'بياناتك',
    canMeasureGlucose: 'هل تستطيع قياس الجلوكوز الآن؟',
    prediction: 'التنبؤ',
    bmi: 'مؤشر كتلة الجسم',
    personalAdvice: 'نصائح شخصية',
    enterValid: 'أدخل أرقاما صحيحة لرؤية التنبؤ.',
    disclaimer: 'هذا التطبيق للتثقيف فقط ولا يشخص السكري.',
    riskLevels: { Low: 'منخفض', Moderate: 'متوسط', High: 'مرتفع' },
  },
};

export const translations = { en, ar, es, secret };

export function resolveLanguage(preference: AppLanguage): SupportedLanguage {
  if (preference !== 'system') {
    return preference;
  }

  const locale = getLocales()[0];

  if (locale?.languageCode === 'ar') {
    return 'ar';
  }

  if (locale?.languageCode === 'es') {
    return 'es';
  }

  return 'en';
}

export function useI18n() {
  const preferences = useAppPreferences();
  const language = resolveLanguage(preferences.language);

  return {
    isRtl: language === 'ar',
    language,
    text: translations[language],
  };
}
