import { getLocales } from 'expo-localization';

import { useAppPreferences, type AppLanguage } from '@/lib/app-preferences';

type SupportedLanguage = 'en' | 'ar' | 'es';

export const languageLabels: Record<AppLanguage, string> = {
  system: 'System',
  en: 'English',
  ar: 'العربية',
  es: 'Español',
};

const en = {
  common: {
    appName: 'Diabeto',
    back: 'Back',
    cancel: 'Cancel',
    clear: 'Clear',
    continue: 'Continue',
    no: 'No',
    optional: 'Optional',
    paste: 'Paste',
    remove: 'Remove',
    save: 'Save',
    send: 'Send',
    wait: 'Wait',
    yes: 'Yes',
  },
  tabs: {
    chat: 'Chat',
    guide: 'Guide',
    home: 'Home',
    log: 'Log',
    predict: 'Predict',
    settings: 'Settings',
  },
  home: {
    subtitle: 'Track risk, understand meals, and chat through healthier choices.',
    today: 'Today',
    quickRiskCheck: 'Start with a quick risk check.',
    predictionHelps: 'Your prediction data also helps Ribbon give more specific food and habit advice.',
    openPredict: 'Open Predict',
    guideBody: 'Balanced meal ideas and simple habit targets.',
    dailyLog: 'Daily Log',
    dailyLogBody: 'Record glucose, sleep, activity, water, meals, and notes.',
    chatBody: 'Ask Ribbon about meals, snacks, habits, or food photos.',
    settingsBody: 'Adjust appearance, language, colors, and Ribbon tone.',
    disclaimer: 'Diabeto is educational and does not replace medical diagnosis or care.',
  },
  onboarding: {
    pageTitles: ['Welcome', 'Terms', 'Health Details', 'Glucose Access', 'Ribbon'],
    startDiabeto: 'Start Diabeto',
    welcomeSubtitle:
      'A diabetes prevention assistant that estimates risk and gives practical habit advice from simple health details.',
    welcomeItems: [
      'Quick lifestyle-based risk estimate',
      'Personal advice from your details',
      'Optional AI chat for meals and food images',
    ],
    beforeStart: 'Before You Start',
    termsTitle: 'Terms of Service',
    termsBody:
      'Diabeto is for education and prevention support only. It does not diagnose diabetes, replace a doctor, or provide emergency care.',
    termsResponsibility:
      'You are responsible for checking important health decisions with a qualified healthcare professional.',
    privacyTitle: 'Privacy Policy',
    privacyBody:
      "Diabeto uses the details you enter to estimate risk and personalize the AI companion's replies. Chat messages and selected images may be sent to the configured Gemini API.",
    privacyWarning:
      'Do not upload private medical documents, IDs, or photos you do not want processed by the AI provider.',
    agreeTerms: 'I agree to the Terms of Service',
    understandPrivacy: 'I understand the Privacy Policy',
    yourDetails: 'Your Details',
    detailsHelp: 'These details help Diabeto make a first estimate. You can adjust them later.',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    years: 'years',
    activity: 'Activity',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    sugaryDrinks: 'Sugary drinks',
    rarely: 'Rarely',
    sometimes: 'Sometimes',
    often: 'Often',
    familyHistory: 'Family history of diabetes',
    glucoseAccess: 'Glucose Access',
    glucoseHelp: 'Not everyone can measure blood glucose at home. Diabeto will not require a glucose value.',
    canMeasureGlucose: 'Are you able to measure your blood glucose right now?',
    glucose: 'Glucose',
    whatThisMeans: 'What this means',
    glucoseMeaning:
      'If you cannot measure glucose, Diabeto estimates risk using age, BMI, family history, activity, and sugary drink habits. A lab glucose or A1C test can make the picture clearer later.',
    meetRibbon: 'Meet Ribbon',
    ribbonBody:
      'Ribbon is your Diabeto health companion. She can help you turn your risk estimate into practical meal ideas, food swaps, activity goals, and safer daily habits.',
    ribbonItems: [
      'Uses your saved health details when you chat',
      'Can review food or drink images you attach',
      'Requires your own Gemini API key from Google AI Studio',
      'Paste the key in Settings before using chat',
      'Keeps advice educational, supportive, and practical',
    ],
  },
  settings: {
    title: 'Settings',
    subtitle: 'Personalize Diabeto and Ribbon.',
    geminiApiKey: 'Gemini API Key',
    keyHelp: 'Ribbon uses your own Google AI Studio key. It stays on this device.',
    keyPlaceholder: 'Paste Gemini API key',
    getApiKey: 'Get an API key',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    colorTheme: 'Color Theme',
    colorThemeLabels: {
      sky: 'Sky',
      mint: 'Mint',
      violet: 'Violet',
      coral: 'Coral',
    },
    ribbonTone: 'Ribbon Tone',
    ribbonToneLabels: {
      warm: 'Warm',
      cold: 'Cold',
      aggressive: 'Aggressive',
      casual: 'Casual',
    },
    ribbonToneDescriptions: {
      warm: 'Default',
      cold: 'also known as Professional',
      aggressive: 'WARNING: You will be heavily insulted if you show images of unhealthy food.',
      casual: 'specifically designed for our gen z users, wassup',
    },
  },
  chat: {
    starter:
      'Hi, I am Ribbon. I can help you plan balanced meals, understand food choices, review images, and build habits that lower diabetes risk.',
    subtitle: 'Your Diabeto health companion.',
    keyNeeded: 'Gemini API key needed',
    usingAll: 'Using Predict data, daily logs, and chat memory',
    usingMemory: 'Using chat memory only',
    keyPanelTitle: 'Ribbon needs your Gemini API key.',
    keyPanelBody: 'Create a key in Google AI Studio, copy it, then paste it in Settings.',
    openSettings: 'Open Settings',
    attachImage: 'Attach image',
    attachImageMessage: 'Choose where the image should come from.',
    takePhoto: 'Take photo',
    choosePhoto: 'Choose photo',
    photoAccessNeeded: 'Photo access is needed before Ribbon can review an image from your library.',
    cameraAccessNeeded: 'Camera access is needed before Ribbon can review a new photo.',
    imageTooLarge: 'That image is too large. Please choose a smaller photo.',
    imageFailed: 'I could not process that image. Please choose a different photo.',
    addKeyBeforeChat: 'Add your Gemini API key in Settings before chatting with Ribbon.',
    imageReviewPrompt: 'Please review this image and give diabetes prevention advice.',
    fallbackError: 'The chatbot could not reply right now. Please try again.',
    promptPlaceholder: 'Ask about meals, habits, or an image...',
    imageAttached: 'Image attached',
    imageReady: 'Ready for Ribbon to review.',
    attach: 'Attach',
    typing: 'Ribbon is preparing a response...',
    quickPrompts: ['Suggest breakfast', 'Suggest lunch', 'Suggest dinner', 'Healthy snack ideas'],
  },
  log: {
    title: 'Daily Log',
    subtitle: 'History for Ribbon and your own review.',
    noLogs: 'No logs yet',
    emptyHelp: "Tap Log your day to add today's health snapshot.",
    logYourDay: 'Log your day',
    glucose: 'Glucose',
    activity: 'Activity',
    sleep: 'Sleep',
    water: 'Water',
    balancedMeals: 'Balanced meals',
    mood: 'Mood',
    notesPlaceholder: 'Meals, cravings, exercise, symptoms...',
    saveLog: 'Save Log',
    noGlucose: 'No glucose',
    noSleep: 'No sleep',
    moods: { steady: 'Steady', good: 'Good', tired: 'Tired', stressed: 'Stressed' },
  },
  guide: {
    title: 'Guide',
    subtitle: 'Simple food and lifestyle targets for lowering diabetes risk.',
    eatTitle: 'What to Eat',
    mealIdeas: [
      'Breakfast: oats with berries, plain yogurt, and nuts.',
      'Lunch: grilled chicken or beans with salad and brown rice.',
      'Dinner: fish, lentils, or tofu with vegetables and a small whole grain portion.',
      'Snack: apple slices, boiled eggs, hummus with carrots, or unsalted nuts.',
    ],
    doTitle: 'What to Do',
    habitIdeas: [
      'Walk for 10 to 20 minutes after meals when possible.',
      'Keep water nearby and avoid buying sugary drinks for home.',
      'Sleep 7 to 9 hours because poor sleep can raise cravings and glucose levels.',
      'Check weight, activity, and glucose trends weekly instead of judging one day.',
    ],
    modelTitle: 'About the Model',
    modelBody:
      'Diabeto uses a lightweight local scoring model based on common risk factors: age, BMI, glucose, family history, activity level, and sugary drink intake.',
    modelFuture:
      'A future version can connect this screen to a trained Python or cloud AI model after you collect a real dataset and decide where predictions should run.',
  },
  predict: {
    subtitle: 'AI-style diabetes risk prediction and habit advice.',
    yourDetails: 'Your Details',
    canMeasureGlucose: 'Can measure glucose now?',
    prediction: 'Prediction',
    bmi: 'BMI',
    personalAdvice: 'Personal advice',
    enterValid: 'Enter valid numbers to see your prediction.',
    disclaimer: 'This app is for education only and does not diagnose diabetes.',
    riskLevels: { Low: 'Low', Moderate: 'Moderate', High: 'High' },
  },
};

const es: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'Atrás',
    cancel: 'Cancelar',
    clear: 'Borrar',
    continue: 'Continuar',
    no: 'No',
    optional: 'Opcional',
    paste: 'Pegar',
    remove: 'Quitar',
    save: 'Guardar',
    send: 'Enviar',
    wait: 'Espera',
    yes: 'Sí',
  },
  tabs: {
    chat: 'Chat',
    guide: 'Guía',
    home: 'Inicio',
    log: 'Registro',
    predict: 'Predicción',
    settings: 'Ajustes',
  },
  home: {
    subtitle: 'Controla el riesgo, entiende tus comidas y conversa sobre mejores decisiones de salud.',
    today: 'Hoy',
    quickRiskCheck: 'Empieza con una revisión rápida del riesgo.',
    predictionHelps: 'Tus datos de predicción también ayudan a Ribbon a dar consejos más específicos sobre comida y hábitos.',
    openPredict: 'Abrir predicción',
    guideBody: 'Ideas de comidas equilibradas y objetivos de hábitos simples.',
    dailyLog: 'Registro diario',
    dailyLogBody: 'Registra glucosa, sueño, actividad, agua, comidas y notas.',
    chatBody: 'Pregunta a Ribbon sobre comidas, snacks, hábitos o fotos de alimentos.',
    settingsBody: 'Ajusta apariencia, idioma, colores y tono de Ribbon.',
    disclaimer: 'Diabeto es educativo y no sustituye el diagnóstico ni la atención médica.',
  },
  onboarding: {
    pageTitles: ['Bienvenida', 'Términos', 'Datos de salud', 'Acceso a glucosa', 'Ribbon'],
    startDiabeto: 'Empezar Diabeto',
    welcomeSubtitle:
      'Un asistente de prevención de diabetes que estima el riesgo y da consejos prácticos de hábitos a partir de datos de salud simples.',
    welcomeItems: [
      'Estimación rápida del riesgo basada en estilo de vida',
      'Consejos personales según tus datos',
      'Chat opcional con IA para comidas e imágenes de alimentos',
    ],
    beforeStart: 'Antes de empezar',
    termsTitle: 'Términos de servicio',
    termsBody:
      'Diabeto es solo para educación y apoyo en prevención. No diagnostica diabetes, no reemplaza a un médico ni ofrece atención de emergencia.',
    termsResponsibility:
      'Eres responsable de revisar las decisiones importantes de salud con un profesional sanitario cualificado.',
    privacyTitle: 'Política de privacidad',
    privacyBody:
      'Diabeto usa los datos que introduces para estimar el riesgo y personalizar las respuestas del asistente de IA. Los mensajes de chat y las imágenes seleccionadas pueden enviarse a la API de Gemini configurada.',
    privacyWarning:
      'No subas documentos médicos privados, identificaciones ni fotos que no quieras que procese el proveedor de IA.',
    agreeTerms: 'Acepto los Términos de servicio',
    understandPrivacy: 'Entiendo la Política de privacidad',
    yourDetails: 'Tus datos',
    detailsHelp: 'Estos datos ayudan a Diabeto a hacer una primera estimación. Puedes ajustarlos después.',
    age: 'Edad',
    height: 'Altura',
    weight: 'Peso',
    years: 'años',
    activity: 'Actividad',
    low: 'Baja',
    moderate: 'Moderada',
    high: 'Alta',
    sugaryDrinks: 'Bebidas azucaradas',
    rarely: 'Rara vez',
    sometimes: 'A veces',
    often: 'A menudo',
    familyHistory: 'Antecedentes familiares de diabetes',
    glucoseAccess: 'Acceso a glucosa',
    glucoseHelp: 'No todo el mundo puede medir la glucosa en casa. Diabeto no exige un valor de glucosa.',
    canMeasureGlucose: '¿Puedes medir tu glucosa en sangre ahora?',
    glucose: 'Glucosa',
    whatThisMeans: 'Qué significa esto',
    glucoseMeaning:
      'Si no puedes medir la glucosa, Diabeto estima el riesgo usando edad, IMC, antecedentes familiares, actividad y hábitos de bebidas azucaradas. Una prueba de glucosa o A1C puede aclarar mejor el panorama más adelante.',
    meetRibbon: 'Conoce a Ribbon',
    ribbonBody:
      'Ribbon es tu acompañante de salud en Diabeto. Puede ayudarte a convertir tu estimación de riesgo en ideas prácticas de comidas, cambios de alimentos, objetivos de actividad y hábitos diarios más seguros.',
    ribbonItems: [
      'Usa tus datos de salud guardados cuando chateas',
      'Puede revisar imágenes de comida o bebida que adjuntes',
      'Requiere tu propia clave de Gemini API de Google AI Studio',
      'Pega la clave en Ajustes antes de usar el chat',
      'Mantiene los consejos educativos, útiles y prácticos',
    ],
  },
  settings: {
    title: 'Ajustes',
    subtitle: 'Personaliza Diabeto y Ribbon.',
    geminiApiKey: 'Clave de Gemini API',
    keyHelp: 'Ribbon usa tu propia clave de Google AI Studio. Permanece en este dispositivo.',
    keyPlaceholder: 'Pega la clave de Gemini API',
    getApiKey: 'Obtener una clave API',
    appearance: 'Apariencia',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    language: 'Idioma',
    colorTheme: 'Tema de color',
    colorThemeLabels: {
      sky: 'Cielo',
      mint: 'Menta',
      violet: 'Violeta',
      coral: 'Coral',
    },
    ribbonTone: 'Tono de Ribbon',
    ribbonToneLabels: {
      warm: 'Cálido',
      cold: 'Profesional',
      aggressive: 'Agresivo',
      casual: 'Casual',
    },
    ribbonToneDescriptions: {
      warm: 'Predeterminado',
      cold: 'conciso, neutral y directo',
      aggressive: 'ADVERTENCIA: Ribbon será muy dura si muestras comida poco saludable.',
      casual: 'diseñado para conversaciones relajadas y actuales',
    },
  },
  chat: {
    starter:
      'Hola, soy Ribbon. Puedo ayudarte a planificar comidas equilibradas, entender elecciones de alimentos, revisar imágenes y crear hábitos que reduzcan el riesgo de diabetes.',
    subtitle: 'Tu acompañante de salud de Diabeto.',
    keyNeeded: 'Se necesita una clave de Gemini API',
    usingAll: 'Usando datos de Predicción, registros diarios y memoria del chat',
    usingMemory: 'Usando solo la memoria del chat',
    keyPanelTitle: 'Ribbon necesita tu clave de Gemini API.',
    keyPanelBody: 'Crea una clave en Google AI Studio, cópiala y pégala en Ajustes.',
    openSettings: 'Abrir Ajustes',
    attachImage: 'Adjuntar imagen',
    attachImageMessage: 'Elige de dónde debe venir la imagen.',
    takePhoto: 'Tomar foto',
    choosePhoto: 'Elegir foto',
    photoAccessNeeded: 'Se necesita acceso a fotos para que Ribbon pueda revisar una imagen de tu biblioteca.',
    cameraAccessNeeded: 'Se necesita acceso a la cámara para que Ribbon pueda revisar una foto nueva.',
    imageTooLarge: 'Esa imagen es demasiado grande. Elige una foto más pequeña.',
    imageFailed: 'No pude procesar esa imagen. Elige otra foto.',
    addKeyBeforeChat: 'Añade tu clave de Gemini API en Ajustes antes de chatear con Ribbon.',
    imageReviewPrompt: 'Revisa esta imagen y da consejos de prevención de diabetes.',
    fallbackError: 'El chatbot no pudo responder ahora. Inténtalo de nuevo.',
    promptPlaceholder: 'Pregunta sobre comidas, hábitos o una imagen...',
    imageAttached: 'Imagen adjunta',
    imageReady: 'Lista para que Ribbon la revise.',
    attach: 'Adjuntar',
    typing: 'Ribbon está preparando una respuesta...',
    quickPrompts: ['Sugerir desayuno', 'Sugerir almuerzo', 'Sugerir cena', 'Ideas de snacks saludables'],
  },
  log: {
    title: 'Registro diario',
    subtitle: 'Historial para Ribbon y para tu propia revisión.',
    noLogs: 'Aún no hay registros',
    emptyHelp: 'Toca Registrar tu día para añadir la instantánea de salud de hoy.',
    logYourDay: 'Registrar tu día',
    glucose: 'Glucosa',
    activity: 'Actividad',
    sleep: 'Sueño',
    water: 'Agua',
    balancedMeals: 'Comidas equilibradas',
    mood: 'Ánimo',
    notesPlaceholder: 'Comidas, antojos, ejercicio, síntomas...',
    saveLog: 'Guardar registro',
    noGlucose: 'Sin glucosa',
    noSleep: 'Sin sueño',
    moods: { steady: 'Estable', good: 'Bien', tired: 'Cansado', stressed: 'Estresado' },
  },
  guide: {
    title: 'Guía',
    subtitle: 'Objetivos simples de alimentación y estilo de vida para reducir el riesgo de diabetes.',
    eatTitle: 'Qué comer',
    mealIdeas: [
      'Desayuno: avena con frutos rojos, yogur natural y frutos secos.',
      'Almuerzo: pollo a la plancha o frijoles con ensalada y arroz integral.',
      'Cena: pescado, lentejas o tofu con verduras y una porción pequeña de cereal integral.',
      'Snack: rodajas de manzana, huevos cocidos, hummus con zanahorias o frutos secos sin sal.',
    ],
    doTitle: 'Qué hacer',
    habitIdeas: [
      'Camina de 10 a 20 minutos después de las comidas cuando sea posible.',
      'Ten agua cerca y evita comprar bebidas azucaradas para casa.',
      'Duerme de 7 a 9 horas porque dormir mal puede aumentar antojos y niveles de glucosa.',
      'Revisa tendencias de peso, actividad y glucosa cada semana en vez de juzgar un solo día.',
    ],
    modelTitle: 'Sobre el modelo',
    modelBody:
      'Diabeto usa un modelo local ligero de puntuación basado en factores de riesgo comunes: edad, IMC, glucosa, antecedentes familiares, nivel de actividad y consumo de bebidas azucaradas.',
    modelFuture:
      'Una versión futura puede conectar esta pantalla a un modelo Python entrenado o a un modelo de IA en la nube cuando tengas un conjunto de datos real y decidas dónde deben ejecutarse las predicciones.',
  },
  predict: {
    subtitle: 'Predicción de riesgo de diabetes estilo IA y consejos de hábitos.',
    yourDetails: 'Tus datos',
    canMeasureGlucose: '¿Puedes medir glucosa ahora?',
    prediction: 'Predicción',
    bmi: 'IMC',
    personalAdvice: 'Consejos personales',
    enterValid: 'Introduce números válidos para ver tu predicción.',
    disclaimer: 'Esta app es solo educativa y no diagnostica diabetes.',
    riskLevels: { Low: 'Bajo', Moderate: 'Moderado', High: 'Alto' },
  },
};

const ar: typeof en = {
  common: {
    appName: 'Diabeto',
    back: 'رجوع',
    cancel: 'إلغاء',
    clear: 'مسح',
    continue: 'متابعة',
    no: 'لا',
    optional: 'اختياري',
    paste: 'لصق',
    remove: 'إزالة',
    save: 'حفظ',
    send: 'إرسال',
    wait: 'انتظر',
    yes: 'نعم',
  },
  tabs: {
    chat: 'الدردشة',
    guide: 'الدليل',
    home: 'الرئيسية',
    log: 'السجل',
    predict: 'التنبؤ',
    settings: 'الإعدادات',
  },
  home: {
    subtitle: 'تابع مستوى الخطورة، وافهم الوجبات، وتحدث عن خيارات صحية أفضل.',
    today: 'اليوم',
    quickRiskCheck: 'ابدأ بفحص سريع لمستوى الخطورة.',
    predictionHelps: 'تساعد بيانات التنبؤ Ribbon على تقديم نصائح غذائية وعادات أكثر دقة.',
    openPredict: 'افتح التنبؤ',
    guideBody: 'أفكار وجبات متوازنة وأهداف عادات بسيطة.',
    dailyLog: 'السجل اليومي',
    dailyLogBody: 'سجل الجلوكوز والنوم والنشاط والماء والوجبات والملاحظات.',
    chatBody: 'اسأل Ribbon عن الوجبات والوجبات الخفيفة والعادات أو صور الطعام.',
    settingsBody: 'عدّل المظهر واللغة والألوان ونبرة Ribbon.',
    disclaimer: 'Diabeto للتثقيف فقط ولا يستبدل التشخيص أو الرعاية الطبية.',
  },
  onboarding: {
    pageTitles: ['الترحيب', 'الشروط', 'بيانات الصحة', 'قياس الجلوكوز', 'Ribbon'],
    startDiabeto: 'ابدأ Diabeto',
    welcomeSubtitle:
      'مساعد للوقاية من السكري يقدر مستوى الخطورة ويقدم نصائح عادات عملية من بيانات صحية بسيطة.',
    welcomeItems: [
      'تقدير سريع للخطورة بناء على نمط الحياة',
      'نصائح شخصية من بياناتك',
      'دردشة اختيارية بالذكاء الاصطناعي للوجبات وصور الطعام',
    ],
    beforeStart: 'قبل أن تبدأ',
    termsTitle: 'شروط الخدمة',
    termsBody:
      'Diabeto مخصص للتثقيف ودعم الوقاية فقط. لا يشخص السكري ولا يستبدل الطبيب ولا يقدم رعاية طارئة.',
    termsResponsibility:
      'أنت مسؤول عن مراجعة القرارات الصحية المهمة مع مختص رعاية صحية مؤهل.',
    privacyTitle: 'سياسة الخصوصية',
    privacyBody:
      'يستخدم Diabeto البيانات التي تدخلها لتقدير الخطورة وتخصيص ردود المرافق الذكي. قد ترسل رسائل الدردشة والصور المحددة إلى Gemini API الذي تم إعداده.',
    privacyWarning:
      'لا ترفع مستندات طبية خاصة أو هويات أو صورا لا تريد معالجتها بواسطة مزود الذكاء الاصطناعي.',
    agreeTerms: 'أوافق على شروط الخدمة',
    understandPrivacy: 'أفهم سياسة الخصوصية',
    yourDetails: 'بياناتك',
    detailsHelp: 'تساعد هذه البيانات Diabeto على إنشاء تقدير أولي. يمكنك تعديلها لاحقا.',
    age: 'العمر',
    height: 'الطول',
    weight: 'الوزن',
    years: 'سنة',
    activity: 'النشاط',
    low: 'منخفض',
    moderate: 'متوسط',
    high: 'مرتفع',
    sugaryDrinks: 'المشروبات السكرية',
    rarely: 'نادرا',
    sometimes: 'أحيانا',
    often: 'غالبا',
    familyHistory: 'تاريخ عائلي للسكري',
    glucoseAccess: 'قياس الجلوكوز',
    glucoseHelp: 'ليس كل شخص يستطيع قياس سكر الدم في المنزل. لن يطلب Diabeto قيمة الجلوكوز.',
    canMeasureGlucose: 'هل تستطيع قياس سكر الدم الآن؟',
    glucose: 'الجلوكوز',
    whatThisMeans: 'ماذا يعني ذلك',
    glucoseMeaning:
      'إذا لم تستطع قياس الجلوكوز، يقدر Diabeto الخطورة باستخدام العمر ومؤشر كتلة الجسم والتاريخ العائلي والنشاط وعادات المشروبات السكرية. يمكن لفحص الجلوكوز أو A1C أن يجعل الصورة أوضح لاحقا.',
    meetRibbon: 'تعرف على Ribbon',
    ribbonBody:
      'Ribbon هو مرافقك الصحي في Diabeto. يمكنه مساعدتك على تحويل تقدير الخطورة إلى أفكار وجبات عملية وبدائل طعام وأهداف نشاط وعادات يومية أكثر أمانا.',
    ribbonItems: [
      'يستخدم بياناتك الصحية المحفوظة عند الدردشة',
      'يمكنه مراجعة صور الطعام أو الشراب التي ترفقها',
      'يتطلب مفتاح Gemini API الخاص بك من Google AI Studio',
      'الصق المفتاح في الإعدادات قبل استخدام الدردشة',
      'يحافظ على النصائح تعليمية وداعمة وعملية',
    ],
  },
  settings: {
    title: 'الإعدادات',
    subtitle: 'خصص Diabeto و Ribbon.',
    geminiApiKey: 'مفتاح Gemini API',
    keyHelp: 'يستخدم Ribbon مفتاح Google AI Studio الخاص بك. يبقى المفتاح على هذا الجهاز.',
    keyPlaceholder: 'الصق مفتاح Gemini API',
    getApiKey: 'احصل على مفتاح API',
    appearance: 'المظهر',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    colorTheme: 'سمة الألوان',
    colorThemeLabels: {
      sky: 'سماوي',
      mint: 'نعناعي',
      violet: 'بنفسجي',
      coral: 'مرجاني',
    },
    ribbonTone: 'نبرة Ribbon',
    ribbonToneLabels: {
      warm: 'دافئة',
      cold: 'مهنية',
      aggressive: 'حادة',
      casual: 'عفوية',
    },
    ribbonToneDescriptions: {
      warm: 'النبرة الافتراضية',
      cold: 'مختصرة ومحايدة ومباشرة',
      aggressive: 'تحذير: ستكون Ribbon قاسية جدا عند عرض أطعمة غير صحية.',
      casual: 'مصممة للمحادثات الخفيفة والعصرية',
    },
  },
  chat: {
    starter:
      'مرحبا، أنا Ribbon. أستطيع مساعدتك في تخطيط وجبات متوازنة وفهم اختيارات الطعام ومراجعة الصور وبناء عادات تقلل خطر السكري.',
    subtitle: 'مرافقك الصحي من Diabeto.',
    keyNeeded: 'مطلوب مفتاح Gemini API',
    usingAll: 'يستخدم بيانات التنبؤ والسجلات اليومية وذاكرة الدردشة',
    usingMemory: 'يستخدم ذاكرة الدردشة فقط',
    keyPanelTitle: 'يحتاج Ribbon إلى مفتاح Gemini API.',
    keyPanelBody: 'أنشئ مفتاحا في Google AI Studio، ثم انسخه والصقه في الإعدادات.',
    openSettings: 'افتح الإعدادات',
    attachImage: 'إرفاق صورة',
    attachImageMessage: 'اختر مصدر الصورة.',
    takePhoto: 'التقاط صورة',
    choosePhoto: 'اختيار صورة',
    photoAccessNeeded: 'يلزم الوصول إلى الصور قبل أن يتمكن Ribbon من مراجعة صورة من مكتبتك.',
    cameraAccessNeeded: 'يلزم الوصول إلى الكاميرا قبل أن يتمكن Ribbon من مراجعة صورة جديدة.',
    imageTooLarge: 'هذه الصورة كبيرة جدا. اختر صورة أصغر.',
    imageFailed: 'لم أتمكن من معالجة هذه الصورة. اختر صورة مختلفة.',
    addKeyBeforeChat: 'أضف مفتاح Gemini API في الإعدادات قبل الدردشة مع Ribbon.',
    imageReviewPrompt: 'يرجى مراجعة هذه الصورة وتقديم نصائح للوقاية من السكري.',
    fallbackError: 'لم يتمكن روبوت الدردشة من الرد الآن. حاول مرة أخرى.',
    promptPlaceholder: 'اسأل عن الوجبات أو العادات أو صورة...',
    imageAttached: 'تم إرفاق صورة',
    imageReady: 'جاهزة لمراجعة Ribbon.',
    attach: 'إرفاق',
    typing: 'Ribbon يجهز ردا...',
    quickPrompts: ['اقترح فطورا', 'اقترح غداء', 'اقترح عشاء', 'أفكار وجبات خفيفة صحية'],
  },
  log: {
    title: 'السجل اليومي',
    subtitle: 'تاريخ للمراجعة بواسطة Ribbon ولك أنت.',
    noLogs: 'لا توجد سجلات بعد',
    emptyHelp: 'اضغط سجل يومك لإضافة لقطة صحية لليوم.',
    logYourDay: 'سجل يومك',
    glucose: 'الجلوكوز',
    activity: 'النشاط',
    sleep: 'النوم',
    water: 'الماء',
    balancedMeals: 'الوجبات المتوازنة',
    mood: 'المزاج',
    notesPlaceholder: 'وجبات، رغبات، تمرين، أعراض...',
    saveLog: 'حفظ السجل',
    noGlucose: 'لا يوجد جلوكوز',
    noSleep: 'لا يوجد نوم',
    moods: { steady: 'مستقر', good: 'جيد', tired: 'متعب', stressed: 'متوتر' },
  },
  guide: {
    title: 'الدليل',
    subtitle: 'أهداف غذاء ونمط حياة بسيطة لتقليل خطر السكري.',
    eatTitle: 'ماذا تأكل',
    mealIdeas: [
      'الفطور: شوفان مع توت ولبن عادي ومكسرات.',
      'الغداء: دجاج مشوي أو فاصوليا مع سلطة وأرز بني.',
      'العشاء: سمك أو عدس أو توفو مع خضار وحصة صغيرة من الحبوب الكاملة.',
      'وجبة خفيفة: شرائح تفاح أو بيض مسلوق أو حمص مع جزر أو مكسرات غير مملحة.',
    ],
    doTitle: 'ماذا تفعل',
    habitIdeas: [
      'امش 10 إلى 20 دقيقة بعد الوجبات عندما يكون ذلك ممكنا.',
      'احتفظ بالماء قريبا وتجنب شراء المشروبات السكرية للمنزل.',
      'نم 7 إلى 9 ساعات لأن قلة النوم قد تزيد الرغبة في الطعام ومستوى الجلوكوز.',
      'راجع اتجاهات الوزن والنشاط والجلوكوز أسبوعيا بدلا من الحكم على يوم واحد.',
    ],
    modelTitle: 'عن النموذج',
    modelBody:
      'يستخدم Diabeto نموذج تسجيل محليا خفيفا يعتمد على عوامل خطورة شائعة: العمر ومؤشر كتلة الجسم والجلوكوز والتاريخ العائلي ومستوى النشاط وتناول المشروبات السكرية.',
    modelFuture:
      'يمكن لإصدار مستقبلي ربط هذه الشاشة بنموذج Python مدرب أو نموذج ذكاء اصطناعي سحابي بعد جمع مجموعة بيانات حقيقية وتحديد مكان تشغيل التنبؤات.',
  },
  predict: {
    subtitle: 'تنبؤ بأسلوب الذكاء الاصطناعي لمخاطر السكري ونصائح عادات.',
    yourDetails: 'بياناتك',
    canMeasureGlucose: 'هل تستطيع قياس الجلوكوز الآن؟',
    prediction: 'التنبؤ',
    bmi: 'مؤشر كتلة الجسم',
    personalAdvice: 'نصائح شخصية',
    enterValid: 'أدخل أرقاما صحيحة لرؤية التنبؤ.',
    disclaimer: 'هذا التطبيق للتثقيف فقط ولا يشخص السكري.',
    riskLevels: { Low: 'منخفض', Moderate: 'متوسط', High: 'مرتفع' },
  },
};

export const translations = { en, ar, es };

export function resolveLanguage(preference: AppLanguage): SupportedLanguage {
  if (preference !== 'system') {
    return preference;
  }

  const locale = getLocales()[0];

  if (locale?.languageCode === 'ar') {
    return 'ar';
  }

  if (locale?.languageCode === 'es') {
    return 'es';
  }

  return 'en';
}

export function useI18n() {
  const preferences = useAppPreferences();
  const language = resolveLanguage(preferences.language);

  return {
    isRtl: language === 'ar',
    language,
    text: translations[language],
  };
}
